// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/v1/event.proto

package buygov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventStatus int32

const (
	EventStatus_EVENT_STATUS_UNSPECIFIED EventStatus = 0
	EventStatus_EVENT_STATUS_DRAFT       EventStatus = 1
	EventStatus_EVENT_STATUS_ACTIVE      EventStatus = 2
	EventStatus_EVENT_STATUS_ENDED       EventStatus = 3
	EventStatus_EVENT_STATUS_ARCHIVED    EventStatus = 4
)

// Enum value maps for EventStatus.
var (
	EventStatus_name = map[int32]string{
		0: "EVENT_STATUS_UNSPECIFIED",
		1: "EVENT_STATUS_DRAFT",
		2: "EVENT_STATUS_ACTIVE",
		3: "EVENT_STATUS_ENDED",
		4: "EVENT_STATUS_ARCHIVED",
	}
	EventStatus_value = map[string]int32{
		"EVENT_STATUS_UNSPECIFIED": 0,
		"EVENT_STATUS_DRAFT":       1,
		"EVENT_STATUS_ACTIVE":      2,
		"EVENT_STATUS_ENDED":       3,
		"EVENT_STATUS_ARCHIVED":    4,
	}
)

func (x EventStatus) Enum() *EventStatus {
	p := new(EventStatus)
	*p = x
	return p
}

func (x EventStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_event_proto_enumTypes[0].Descriptor()
}

func (EventStatus) Type() protoreflect.EnumType {
	return &file_api_v1_event_proto_enumTypes[0]
}

func (x EventStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventStatus.Descriptor instead.
func (EventStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{0}
}

type RegistrationStatus int32

const (
	RegistrationStatus_REGISTRATION_STATUS_UNSPECIFIED RegistrationStatus = 0
	RegistrationStatus_REGISTRATION_STATUS_PENDING     RegistrationStatus = 1
	RegistrationStatus_REGISTRATION_STATUS_CONFIRMED   RegistrationStatus = 2
	RegistrationStatus_REGISTRATION_STATUS_CANCELLED   RegistrationStatus = 3
)

// Enum value maps for RegistrationStatus.
var (
	RegistrationStatus_name = map[int32]string{
		0: "REGISTRATION_STATUS_UNSPECIFIED",
		1: "REGISTRATION_STATUS_PENDING",
		2: "REGISTRATION_STATUS_CONFIRMED",
		3: "REGISTRATION_STATUS_CANCELLED",
	}
	RegistrationStatus_value = map[string]int32{
		"REGISTRATION_STATUS_UNSPECIFIED": 0,
		"REGISTRATION_STATUS_PENDING":     1,
		"REGISTRATION_STATUS_CONFIRMED":   2,
		"REGISTRATION_STATUS_CANCELLED":   3,
	}
)

func (x RegistrationStatus) Enum() *RegistrationStatus {
	p := new(RegistrationStatus)
	*p = x
	return p
}

func (x RegistrationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegistrationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_event_proto_enumTypes[1].Descriptor()
}

func (RegistrationStatus) Type() protoreflect.EnumType {
	return &file_api_v1_event_proto_enumTypes[1]
}

func (x RegistrationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegistrationStatus.Descriptor instead.
func (RegistrationStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{1}
}

// ...
type UpdateRegistrationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RegistrationId string                 `protobuf:"bytes,1,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	Items          []*RegisterItem        `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	ContactInfo    string                 `protobuf:"bytes,3,opt,name=contact_info,json=contactInfo,proto3" json:"contact_info,omitempty"`
	Notes          string                 `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateRegistrationRequest) Reset() {
	*x = UpdateRegistrationRequest{}
	mi := &file_api_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRegistrationRequest) ProtoMessage() {}

func (x *UpdateRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRegistrationRequest.ProtoReflect.Descriptor instead.
func (*UpdateRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateRegistrationRequest) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

func (x *UpdateRegistrationRequest) GetItems() []*RegisterItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *UpdateRegistrationRequest) GetContactInfo() string {
	if x != nil {
		return x.ContactInfo
	}
	return ""
}

func (x *UpdateRegistrationRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type UpdateRegistrationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RegistrationId string                 `protobuf:"bytes,1,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	Status         RegistrationStatus     `protobuf:"varint,2,opt,name=status,proto3,enum=buygo.v1.RegistrationStatus" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateRegistrationResponse) Reset() {
	*x = UpdateRegistrationResponse{}
	mi := &file_api_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRegistrationResponse) ProtoMessage() {}

func (x *UpdateRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRegistrationResponse.ProtoReflect.Descriptor instead.
func (*UpdateRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateRegistrationResponse) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

func (x *UpdateRegistrationResponse) GetStatus() RegistrationStatus {
	if x != nil {
		return x.Status
	}
	return RegistrationStatus_REGISTRATION_STATUS_UNSPECIFIED
}

type UpdateRegistrationStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RegistrationId string                 `protobuf:"bytes,1,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	Status         RegistrationStatus     `protobuf:"varint,2,opt,name=status,proto3,enum=buygo.v1.RegistrationStatus" json:"status,omitempty"`
	PaymentStatus  PaymentStatus          `protobuf:"varint,3,opt,name=payment_status,json=paymentStatus,proto3,enum=buygo.v1.PaymentStatus" json:"payment_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateRegistrationStatusRequest) Reset() {
	*x = UpdateRegistrationStatusRequest{}
	mi := &file_api_v1_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRegistrationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRegistrationStatusRequest) ProtoMessage() {}

func (x *UpdateRegistrationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRegistrationStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateRegistrationStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRegistrationStatusRequest) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

func (x *UpdateRegistrationStatusRequest) GetStatus() RegistrationStatus {
	if x != nil {
		return x.Status
	}
	return RegistrationStatus_REGISTRATION_STATUS_UNSPECIFIED
}

func (x *UpdateRegistrationStatusRequest) GetPaymentStatus() PaymentStatus {
	if x != nil {
		return x.PaymentStatus
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

type UpdateRegistrationStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RegistrationId string                 `protobuf:"bytes,1,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	Status         RegistrationStatus     `protobuf:"varint,2,opt,name=status,proto3,enum=buygo.v1.RegistrationStatus" json:"status,omitempty"`
	PaymentStatus  PaymentStatus          `protobuf:"varint,3,opt,name=payment_status,json=paymentStatus,proto3,enum=buygo.v1.PaymentStatus" json:"payment_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateRegistrationStatusResponse) Reset() {
	*x = UpdateRegistrationStatusResponse{}
	mi := &file_api_v1_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRegistrationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRegistrationStatusResponse) ProtoMessage() {}

func (x *UpdateRegistrationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRegistrationStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateRegistrationStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRegistrationStatusResponse) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

func (x *UpdateRegistrationStatusResponse) GetStatus() RegistrationStatus {
	if x != nil {
		return x.Status
	}
	return RegistrationStatus_REGISTRATION_STATUS_UNSPECIFIED
}

func (x *UpdateRegistrationStatusResponse) GetPaymentStatus() PaymentStatus {
	if x != nil {
		return x.PaymentStatus
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

type Event struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CoverImageUrl        string                 `protobuf:"bytes,4,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`
	Status               EventStatus            `protobuf:"varint,5,opt,name=status,proto3,enum=buygo.v1.EventStatus" json:"status,omitempty"`
	StartTime            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	RegistrationDeadline *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=registration_deadline,json=registrationDeadline,proto3" json:"registration_deadline,omitempty"`
	Location             string                 `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	Creator              *User                  `protobuf:"bytes,10,opt,name=creator,proto3" json:"creator,omitempty"`
	Managers             []*User                `protobuf:"bytes,11,rep,name=managers,proto3" json:"managers,omitempty"`
	PaymentMethods       []string               `protobuf:"bytes,12,rep,name=payment_methods,json=paymentMethods,proto3" json:"payment_methods,omitempty"`
	Items                []*EventItem           `protobuf:"bytes,13,rep,name=items,proto3" json:"items,omitempty"`
	AllowModification    bool                   `protobuf:"varint,14,opt,name=allow_modification,json=allowModification,proto3" json:"allow_modification,omitempty"`
	Discounts            []*DiscountRule        `protobuf:"bytes,15,rep,name=discounts,proto3" json:"discounts,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_v1_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{4}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *Event) GetStatus() EventStatus {
	if x != nil {
		return x.Status
	}
	return EventStatus_EVENT_STATUS_UNSPECIFIED
}

func (x *Event) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Event) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Event) GetRegistrationDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.RegistrationDeadline
	}
	return nil
}

func (x *Event) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Event) GetCreator() *User {
	if x != nil {
		return x.Creator
	}
	return nil
}

func (x *Event) GetManagers() []*User {
	if x != nil {
		return x.Managers
	}
	return nil
}

func (x *Event) GetPaymentMethods() []string {
	if x != nil {
		return x.PaymentMethods
	}
	return nil
}

func (x *Event) GetItems() []*EventItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Event) GetAllowModification() bool {
	if x != nil {
		return x.AllowModification
	}
	return false
}

func (x *Event) GetDiscounts() []*DiscountRule {
	if x != nil {
		return x.Discounts
	}
	return nil
}

type EventItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price           int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	MinParticipants int32                  `protobuf:"varint,4,opt,name=min_participants,json=minParticipants,proto3" json:"min_participants,omitempty"`
	MaxParticipants int32                  `protobuf:"varint,5,opt,name=max_participants,json=maxParticipants,proto3" json:"max_participants,omitempty"`
	StartTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	AllowMultiple   bool                   `protobuf:"varint,8,opt,name=allow_multiple,json=allowMultiple,proto3" json:"allow_multiple,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EventItem) Reset() {
	*x = EventItem{}
	mi := &file_api_v1_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventItem) ProtoMessage() {}

func (x *EventItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventItem.ProtoReflect.Descriptor instead.
func (*EventItem) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{5}
}

func (x *EventItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventItem) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *EventItem) GetMinParticipants() int32 {
	if x != nil {
		return x.MinParticipants
	}
	return 0
}

func (x *EventItem) GetMaxParticipants() int32 {
	if x != nil {
		return x.MaxParticipants
	}
	return 0
}

func (x *EventItem) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *EventItem) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *EventItem) GetAllowMultiple() bool {
	if x != nil {
		return x.AllowMultiple
	}
	return false
}

type DiscountRule struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MinQuantity      int32                  `protobuf:"varint,1,opt,name=min_quantity,json=minQuantity,proto3" json:"min_quantity,omitempty"`                  // Minimum items (sum of all items in registration)
	DiscountAmount   int64                  `protobuf:"varint,2,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`         // Fixed amount off (e.g. 100 TWD)
	MinDistinctItems int32                  `protobuf:"varint,3,opt,name=min_distinct_items,json=minDistinctItems,proto3" json:"min_distinct_items,omitempty"` // Could add percentage later
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DiscountRule) Reset() {
	*x = DiscountRule{}
	mi := &file_api_v1_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscountRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscountRule) ProtoMessage() {}

func (x *DiscountRule) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscountRule.ProtoReflect.Descriptor instead.
func (*DiscountRule) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{6}
}

func (x *DiscountRule) GetMinQuantity() int32 {
	if x != nil {
		return x.MinQuantity
	}
	return 0
}

func (x *DiscountRule) GetDiscountAmount() int64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *DiscountRule) GetMinDistinctItems() int32 {
	if x != nil {
		return x.MinDistinctItems
	}
	return 0
}

type GetEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_api_v1_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{7}
}

func (x *GetEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type GetEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventResponse) Reset() {
	*x = GetEventResponse{}
	mi := &file_api_v1_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventResponse) ProtoMessage() {}

func (x *GetEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventResponse.ProtoReflect.Descriptor instead.
func (*GetEventResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{8}
}

func (x *GetEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type CreateEventRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Title                string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	StartTime            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Discounts            []*DiscountRule        `protobuf:"bytes,5,rep,name=discounts,proto3" json:"discounts,omitempty"`
	Items                []*EventItem           `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty"`
	Location             string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	CoverImageUrl        string                 `protobuf:"bytes,8,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`
	RegistrationDeadline *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=registration_deadline,json=registrationDeadline,proto3" json:"registration_deadline,omitempty"`
	PaymentMethods       []string               `protobuf:"bytes,10,rep,name=payment_methods,json=paymentMethods,proto3" json:"payment_methods,omitempty"`
	AllowModification    bool                   `protobuf:"varint,11,opt,name=allow_modification,json=allowModification,proto3" json:"allow_modification,omitempty"`
	ManagerIds           []string               `protobuf:"bytes,12,rep,name=manager_ids,json=managerIds,proto3" json:"manager_ids,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_api_v1_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{9}
}

func (x *CreateEventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateEventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateEventRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CreateEventRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *CreateEventRequest) GetDiscounts() []*DiscountRule {
	if x != nil {
		return x.Discounts
	}
	return nil
}

func (x *CreateEventRequest) GetItems() []*EventItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreateEventRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateEventRequest) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *CreateEventRequest) GetRegistrationDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.RegistrationDeadline
	}
	return nil
}

func (x *CreateEventRequest) GetPaymentMethods() []string {
	if x != nil {
		return x.PaymentMethods
	}
	return nil
}

func (x *CreateEventRequest) GetAllowModification() bool {
	if x != nil {
		return x.AllowModification
	}
	return false
}

func (x *CreateEventRequest) GetManagerIds() []string {
	if x != nil {
		return x.ManagerIds
	}
	return nil
}

type CreateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventResponse) Reset() {
	*x = CreateEventResponse{}
	mi := &file_api_v1_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventResponse) ProtoMessage() {}

func (x *CreateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventResponse.ProtoReflect.Descriptor instead.
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{10}
}

func (x *CreateEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type UpdateEventRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EventId           string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Title             string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartTime         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime           *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Location          string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	CoverImageUrl     string                 `protobuf:"bytes,7,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`
	AllowModification bool                   `protobuf:"varint,8,opt,name=allow_modification,json=allowModification,proto3" json:"allow_modification,omitempty"`
	Items             []*EventItem           `protobuf:"bytes,9,rep,name=items,proto3" json:"items,omitempty"` // Full replace strategy for items
	ManagerIds        []string               `protobuf:"bytes,10,rep,name=manager_ids,json=managerIds,proto3" json:"manager_ids,omitempty"`
	Discounts         []*DiscountRule        `protobuf:"bytes,11,rep,name=discounts,proto3" json:"discounts,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateEventRequest) Reset() {
	*x = UpdateEventRequest{}
	mi := &file_api_v1_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventRequest) ProtoMessage() {}

func (x *UpdateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UpdateEventRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateEventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateEventRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *UpdateEventRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *UpdateEventRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateEventRequest) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *UpdateEventRequest) GetAllowModification() bool {
	if x != nil {
		return x.AllowModification
	}
	return false
}

func (x *UpdateEventRequest) GetItems() []*EventItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *UpdateEventRequest) GetManagerIds() []string {
	if x != nil {
		return x.ManagerIds
	}
	return nil
}

func (x *UpdateEventRequest) GetDiscounts() []*DiscountRule {
	if x != nil {
		return x.Discounts
	}
	return nil
}

type UpdateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventResponse) Reset() {
	*x = UpdateEventResponse{}
	mi := &file_api_v1_event_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventResponse) ProtoMessage() {}

func (x *UpdateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventResponse.ProtoReflect.Descriptor instead.
func (*UpdateEventResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type UpdateEventStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Status        EventStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=buygo.v1.EventStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventStatusRequest) Reset() {
	*x = UpdateEventStatusRequest{}
	mi := &file_api_v1_event_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventStatusRequest) ProtoMessage() {}

func (x *UpdateEventStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateEventStatusRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UpdateEventStatusRequest) GetStatus() EventStatus {
	if x != nil {
		return x.Status
	}
	return EventStatus_EVENT_STATUS_UNSPECIFIED
}

type UpdateEventStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventStatusResponse) Reset() {
	*x = UpdateEventStatusResponse{}
	mi := &file_api_v1_event_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventStatusResponse) ProtoMessage() {}

func (x *UpdateEventStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateEventStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateEventStatusResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_api_v1_event_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{15}
}

func (x *ListEventsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListEventsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_api_v1_event_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{16}
}

func (x *ListEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListEventsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListManagerEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManagerEventsRequest) Reset() {
	*x = ListManagerEventsRequest{}
	mi := &file_api_v1_event_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManagerEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManagerEventsRequest) ProtoMessage() {}

func (x *ListManagerEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManagerEventsRequest.ProtoReflect.Descriptor instead.
func (*ListManagerEventsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{17}
}

func (x *ListManagerEventsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListManagerEventsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListManagerEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManagerEventsResponse) Reset() {
	*x = ListManagerEventsResponse{}
	mi := &file_api_v1_event_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManagerEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManagerEventsResponse) ProtoMessage() {}

func (x *ListManagerEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManagerEventsResponse.ProtoReflect.Descriptor instead.
func (*ListManagerEventsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{18}
}

func (x *ListManagerEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListManagerEventsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type RegisterEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Items         []*RegisterItem        `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	ContactInfo   string                 `protobuf:"bytes,3,opt,name=contact_info,json=contactInfo,proto3" json:"contact_info,omitempty"` // JSON or Struct
	Notes         string                 `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterEventRequest) Reset() {
	*x = RegisterEventRequest{}
	mi := &file_api_v1_event_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterEventRequest) ProtoMessage() {}

func (x *RegisterEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterEventRequest.ProtoReflect.Descriptor instead.
func (*RegisterEventRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{19}
}

func (x *RegisterEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RegisterEventRequest) GetItems() []*RegisterItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *RegisterEventRequest) GetContactInfo() string {
	if x != nil {
		return x.ContactInfo
	}
	return ""
}

func (x *RegisterEventRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type RegisterItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventItemId   string                 `protobuf:"bytes,1,opt,name=event_item_id,json=eventItemId,proto3" json:"event_item_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"` // Usually 1 for events, but maybe guest tickets
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterItem) Reset() {
	*x = RegisterItem{}
	mi := &file_api_v1_event_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterItem) ProtoMessage() {}

func (x *RegisterItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterItem.ProtoReflect.Descriptor instead.
func (*RegisterItem) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{20}
}

func (x *RegisterItem) GetEventItemId() string {
	if x != nil {
		return x.EventItemId
	}
	return ""
}

func (x *RegisterItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type RegisterEventResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RegistrationId string                 `protobuf:"bytes,1,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	Status         RegistrationStatus     `protobuf:"varint,2,opt,name=status,proto3,enum=buygo.v1.RegistrationStatus" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterEventResponse) Reset() {
	*x = RegisterEventResponse{}
	mi := &file_api_v1_event_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterEventResponse) ProtoMessage() {}

func (x *RegisterEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterEventResponse.ProtoReflect.Descriptor instead.
func (*RegisterEventResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{21}
}

func (x *RegisterEventResponse) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

func (x *RegisterEventResponse) GetStatus() RegistrationStatus {
	if x != nil {
		return x.Status
	}
	return RegistrationStatus_REGISTRATION_STATUS_UNSPECIFIED
}

type CancelRegistrationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RegistrationId string                 `protobuf:"bytes,1,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelRegistrationRequest) Reset() {
	*x = CancelRegistrationRequest{}
	mi := &file_api_v1_event_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRegistrationRequest) ProtoMessage() {}

func (x *CancelRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRegistrationRequest.ProtoReflect.Descriptor instead.
func (*CancelRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{22}
}

func (x *CancelRegistrationRequest) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

type CancelRegistrationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RegistrationId string                 `protobuf:"bytes,1,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	Status         RegistrationStatus     `protobuf:"varint,2,opt,name=status,proto3,enum=buygo.v1.RegistrationStatus" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelRegistrationResponse) Reset() {
	*x = CancelRegistrationResponse{}
	mi := &file_api_v1_event_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRegistrationResponse) ProtoMessage() {}

func (x *CancelRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRegistrationResponse.ProtoReflect.Descriptor instead.
func (*CancelRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{23}
}

func (x *CancelRegistrationResponse) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

func (x *CancelRegistrationResponse) GetStatus() RegistrationStatus {
	if x != nil {
		return x.Status
	}
	return RegistrationStatus_REGISTRATION_STATUS_UNSPECIFIED
}

type Registration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        RegistrationStatus     `protobuf:"varint,4,opt,name=status,proto3,enum=buygo.v1.RegistrationStatus" json:"status,omitempty"`
	PaymentStatus PaymentStatus          `protobuf:"varint,5,opt,name=payment_status,json=paymentStatus,proto3,enum=buygo.v1.PaymentStatus" json:"payment_status,omitempty"`
	ContactInfo   string                 `protobuf:"bytes,6,opt,name=contact_info,json=contactInfo,proto3" json:"contact_info,omitempty"`
	Notes         string                 `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	SelectedItems []*RegisterItem        `protobuf:"bytes,8,rep,name=selected_items,json=selectedItems,proto3" json:"selected_items,omitempty"`
	User          *User                  `protobuf:"bytes,9,opt,name=user,proto3" json:"user,omitempty"`
	// Snapshots at time of order
	TotalAmount     int64 `protobuf:"varint,10,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	DiscountApplied int64 `protobuf:"varint,11,opt,name=discount_applied,json=discountApplied,proto3" json:"discount_applied,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Registration) Reset() {
	*x = Registration{}
	mi := &file_api_v1_event_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registration) ProtoMessage() {}

func (x *Registration) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registration.ProtoReflect.Descriptor instead.
func (*Registration) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{24}
}

func (x *Registration) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Registration) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Registration) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Registration) GetStatus() RegistrationStatus {
	if x != nil {
		return x.Status
	}
	return RegistrationStatus_REGISTRATION_STATUS_UNSPECIFIED
}

func (x *Registration) GetPaymentStatus() PaymentStatus {
	if x != nil {
		return x.PaymentStatus
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *Registration) GetContactInfo() string {
	if x != nil {
		return x.ContactInfo
	}
	return ""
}

func (x *Registration) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Registration) GetSelectedItems() []*RegisterItem {
	if x != nil {
		return x.SelectedItems
	}
	return nil
}

func (x *Registration) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Registration) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Registration) GetDiscountApplied() int64 {
	if x != nil {
		return x.DiscountApplied
	}
	return 0
}

type GetMyRegistrationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyRegistrationsRequest) Reset() {
	*x = GetMyRegistrationsRequest{}
	mi := &file_api_v1_event_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyRegistrationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyRegistrationsRequest) ProtoMessage() {}

func (x *GetMyRegistrationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyRegistrationsRequest.ProtoReflect.Descriptor instead.
func (*GetMyRegistrationsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{25}
}

type GetMyRegistrationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registrations []*Registration        `protobuf:"bytes,1,rep,name=registrations,proto3" json:"registrations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyRegistrationsResponse) Reset() {
	*x = GetMyRegistrationsResponse{}
	mi := &file_api_v1_event_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyRegistrationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyRegistrationsResponse) ProtoMessage() {}

func (x *GetMyRegistrationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyRegistrationsResponse.ProtoReflect.Descriptor instead.
func (*GetMyRegistrationsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{26}
}

func (x *GetMyRegistrationsResponse) GetRegistrations() []*Registration {
	if x != nil {
		return x.Registrations
	}
	return nil
}

type ListEventRegistrationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventRegistrationsRequest) Reset() {
	*x = ListEventRegistrationsRequest{}
	mi := &file_api_v1_event_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventRegistrationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventRegistrationsRequest) ProtoMessage() {}

func (x *ListEventRegistrationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventRegistrationsRequest.ProtoReflect.Descriptor instead.
func (*ListEventRegistrationsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{27}
}

func (x *ListEventRegistrationsRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type ListEventRegistrationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registrations []*Registration        `protobuf:"bytes,1,rep,name=registrations,proto3" json:"registrations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventRegistrationsResponse) Reset() {
	*x = ListEventRegistrationsResponse{}
	mi := &file_api_v1_event_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventRegistrationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventRegistrationsResponse) ProtoMessage() {}

func (x *ListEventRegistrationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventRegistrationsResponse.ProtoReflect.Descriptor instead.
func (*ListEventRegistrationsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{28}
}

func (x *ListEventRegistrationsResponse) GetRegistrations() []*Registration {
	if x != nil {
		return x.Registrations
	}
	return nil
}

var File_api_v1_event_proto protoreflect.FileDescriptor

const file_api_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x12api/v1/event.proto\x12\bbuygo.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11api/v1/auth.proto\x1a\x15api/v1/groupbuy.proto\"\xab\x01\n" +
	"\x19UpdateRegistrationRequest\x12'\n" +
	"\x0fregistration_id\x18\x01 \x01(\tR\x0eregistrationId\x12,\n" +
	"\x05items\x18\x02 \x03(\v2\x16.buygo.v1.RegisterItemR\x05items\x12!\n" +
	"\fcontact_info\x18\x03 \x01(\tR\vcontactInfo\x12\x14\n" +
	"\x05notes\x18\x04 \x01(\tR\x05notes\"{\n" +
	"\x1aUpdateRegistrationResponse\x12'\n" +
	"\x0fregistration_id\x18\x01 \x01(\tR\x0eregistrationId\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.buygo.v1.RegistrationStatusR\x06status\"\xc0\x01\n" +
	"\x1fUpdateRegistrationStatusRequest\x12'\n" +
	"\x0fregistration_id\x18\x01 \x01(\tR\x0eregistrationId\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.buygo.v1.RegistrationStatusR\x06status\x12>\n" +
	"\x0epayment_status\x18\x03 \x01(\x0e2\x17.buygo.v1.PaymentStatusR\rpaymentStatus\"\xc1\x01\n" +
	" UpdateRegistrationStatusResponse\x12'\n" +
	"\x0fregistration_id\x18\x01 \x01(\tR\x0eregistrationId\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.buygo.v1.RegistrationStatusR\x06status\x12>\n" +
	"\x0epayment_status\x18\x03 \x01(\x0e2\x17.buygo.v1.PaymentStatusR\rpaymentStatus\"\x94\x05\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12&\n" +
	"\x0fcover_image_url\x18\x04 \x01(\tR\rcoverImageUrl\x12-\n" +
	"\x06status\x18\x05 \x01(\x0e2\x15.buygo.v1.EventStatusR\x06status\x129\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12O\n" +
	"\x15registration_deadline\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x14registrationDeadline\x12\x1a\n" +
	"\blocation\x18\t \x01(\tR\blocation\x12(\n" +
	"\acreator\x18\n" +
	" \x01(\v2\x0e.buygo.v1.UserR\acreator\x12*\n" +
	"\bmanagers\x18\v \x03(\v2\x0e.buygo.v1.UserR\bmanagers\x12'\n" +
	"\x0fpayment_methods\x18\f \x03(\tR\x0epaymentMethods\x12)\n" +
	"\x05items\x18\r \x03(\v2\x13.buygo.v1.EventItemR\x05items\x12-\n" +
	"\x12allow_modification\x18\x0e \x01(\bR\x11allowModification\x124\n" +
	"\tdiscounts\x18\x0f \x03(\v2\x16.buygo.v1.DiscountRuleR\tdiscounts\"\xb4\x02\n" +
	"\tEventItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12)\n" +
	"\x10min_participants\x18\x04 \x01(\x05R\x0fminParticipants\x12)\n" +
	"\x10max_participants\x18\x05 \x01(\x05R\x0fmaxParticipants\x129\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12%\n" +
	"\x0eallow_multiple\x18\b \x01(\bR\rallowMultiple\"\x88\x01\n" +
	"\fDiscountRule\x12!\n" +
	"\fmin_quantity\x18\x01 \x01(\x05R\vminQuantity\x12'\n" +
	"\x0fdiscount_amount\x18\x02 \x01(\x03R\x0ediscountAmount\x12,\n" +
	"\x12min_distinct_items\x18\x03 \x01(\x05R\x10minDistinctItems\",\n" +
	"\x0fGetEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"9\n" +
	"\x10GetEventResponse\x12%\n" +
	"\x05event\x18\x01 \x01(\v2\x0f.buygo.v1.EventR\x05event\"\xad\x04\n" +
	"\x12CreateEventRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x124\n" +
	"\tdiscounts\x18\x05 \x03(\v2\x16.buygo.v1.DiscountRuleR\tdiscounts\x12)\n" +
	"\x05items\x18\x06 \x03(\v2\x13.buygo.v1.EventItemR\x05items\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12&\n" +
	"\x0fcover_image_url\x18\b \x01(\tR\rcoverImageUrl\x12O\n" +
	"\x15registration_deadline\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x14registrationDeadline\x12'\n" +
	"\x0fpayment_methods\x18\n" +
	" \x03(\tR\x0epaymentMethods\x12-\n" +
	"\x12allow_modification\x18\v \x01(\bR\x11allowModification\x12\x1f\n" +
	"\vmanager_ids\x18\f \x03(\tR\n" +
	"managerIds\"<\n" +
	"\x13CreateEventResponse\x12%\n" +
	"\x05event\x18\x01 \x01(\v2\x0f.buygo.v1.EventR\x05event\"\xce\x03\n" +
	"\x12UpdateEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\x12&\n" +
	"\x0fcover_image_url\x18\a \x01(\tR\rcoverImageUrl\x12-\n" +
	"\x12allow_modification\x18\b \x01(\bR\x11allowModification\x12)\n" +
	"\x05items\x18\t \x03(\v2\x13.buygo.v1.EventItemR\x05items\x12\x1f\n" +
	"\vmanager_ids\x18\n" +
	" \x03(\tR\n" +
	"managerIds\x124\n" +
	"\tdiscounts\x18\v \x03(\v2\x16.buygo.v1.DiscountRuleR\tdiscounts\"<\n" +
	"\x13UpdateEventResponse\x12%\n" +
	"\x05event\x18\x01 \x01(\v2\x0f.buygo.v1.EventR\x05event\"d\n" +
	"\x18UpdateEventStatusRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.buygo.v1.EventStatusR\x06status\"B\n" +
	"\x19UpdateEventStatusResponse\x12%\n" +
	"\x05event\x18\x01 \x01(\v2\x0f.buygo.v1.EventR\x05event\"O\n" +
	"\x11ListEventsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"e\n" +
	"\x12ListEventsResponse\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.buygo.v1.EventR\x06events\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"V\n" +
	"\x18ListManagerEventsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"l\n" +
	"\x19ListManagerEventsResponse\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.buygo.v1.EventR\x06events\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x98\x01\n" +
	"\x14RegisterEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12,\n" +
	"\x05items\x18\x02 \x03(\v2\x16.buygo.v1.RegisterItemR\x05items\x12!\n" +
	"\fcontact_info\x18\x03 \x01(\tR\vcontactInfo\x12\x14\n" +
	"\x05notes\x18\x04 \x01(\tR\x05notes\"N\n" +
	"\fRegisterItem\x12\"\n" +
	"\revent_item_id\x18\x01 \x01(\tR\veventItemId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"v\n" +
	"\x15RegisterEventResponse\x12'\n" +
	"\x0fregistration_id\x18\x01 \x01(\tR\x0eregistrationId\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.buygo.v1.RegistrationStatusR\x06status\"D\n" +
	"\x19CancelRegistrationRequest\x12'\n" +
	"\x0fregistration_id\x18\x01 \x01(\tR\x0eregistrationId\"{\n" +
	"\x1aCancelRegistrationResponse\x12'\n" +
	"\x0fregistration_id\x18\x01 \x01(\tR\x0eregistrationId\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.buygo.v1.RegistrationStatusR\x06status\"\xb2\x03\n" +
	"\fRegistration\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x124\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1c.buygo.v1.RegistrationStatusR\x06status\x12>\n" +
	"\x0epayment_status\x18\x05 \x01(\x0e2\x17.buygo.v1.PaymentStatusR\rpaymentStatus\x12!\n" +
	"\fcontact_info\x18\x06 \x01(\tR\vcontactInfo\x12\x14\n" +
	"\x05notes\x18\a \x01(\tR\x05notes\x12=\n" +
	"\x0eselected_items\x18\b \x03(\v2\x16.buygo.v1.RegisterItemR\rselectedItems\x12\"\n" +
	"\x04user\x18\t \x01(\v2\x0e.buygo.v1.UserR\x04user\x12!\n" +
	"\ftotal_amount\x18\n" +
	" \x01(\x03R\vtotalAmount\x12)\n" +
	"\x10discount_applied\x18\v \x01(\x03R\x0fdiscountApplied\"\x1b\n" +
	"\x19GetMyRegistrationsRequest\"Z\n" +
	"\x1aGetMyRegistrationsResponse\x12<\n" +
	"\rregistrations\x18\x01 \x03(\v2\x16.buygo.v1.RegistrationR\rregistrations\":\n" +
	"\x1dListEventRegistrationsRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"^\n" +
	"\x1eListEventRegistrationsResponse\x12<\n" +
	"\rregistrations\x18\x01 \x03(\v2\x16.buygo.v1.RegistrationR\rregistrations*\x8f\x01\n" +
	"\vEventStatus\x12\x1c\n" +
	"\x18EVENT_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EVENT_STATUS_DRAFT\x10\x01\x12\x17\n" +
	"\x13EVENT_STATUS_ACTIVE\x10\x02\x12\x16\n" +
	"\x12EVENT_STATUS_ENDED\x10\x03\x12\x19\n" +
	"\x15EVENT_STATUS_ARCHIVED\x10\x04*\xa0\x01\n" +
	"\x12RegistrationStatus\x12#\n" +
	"\x1fREGISTRATION_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bREGISTRATION_STATUS_PENDING\x10\x01\x12!\n" +
	"\x1dREGISTRATION_STATUS_CONFIRMED\x10\x02\x12!\n" +
	"\x1dREGISTRATION_STATUS_CANCELLED\x10\x032\xc3\b\n" +
	"\fEventService\x12J\n" +
	"\vCreateEvent\x12\x1c.buygo.v1.CreateEventRequest\x1a\x1d.buygo.v1.CreateEventResponse\x12G\n" +
	"\n" +
	"ListEvents\x12\x1b.buygo.v1.ListEventsRequest\x1a\x1c.buygo.v1.ListEventsResponse\x12\\\n" +
	"\x11ListManagerEvents\x12\".buygo.v1.ListManagerEventsRequest\x1a#.buygo.v1.ListManagerEventsResponse\x12A\n" +
	"\bGetEvent\x12\x19.buygo.v1.GetEventRequest\x1a\x1a.buygo.v1.GetEventResponse\x12P\n" +
	"\rRegisterEvent\x12\x1e.buygo.v1.RegisterEventRequest\x1a\x1f.buygo.v1.RegisterEventResponse\x12_\n" +
	"\x12UpdateRegistration\x12#.buygo.v1.UpdateRegistrationRequest\x1a$.buygo.v1.UpdateRegistrationResponse\x12q\n" +
	"\x18UpdateRegistrationStatus\x12).buygo.v1.UpdateRegistrationStatusRequest\x1a*.buygo.v1.UpdateRegistrationStatusResponse\x12_\n" +
	"\x12CancelRegistration\x12#.buygo.v1.CancelRegistrationRequest\x1a$.buygo.v1.CancelRegistrationResponse\x12_\n" +
	"\x12GetMyRegistrations\x12#.buygo.v1.GetMyRegistrationsRequest\x1a$.buygo.v1.GetMyRegistrationsResponse\x12k\n" +
	"\x16ListEventRegistrations\x12'.buygo.v1.ListEventRegistrationsRequest\x1a(.buygo.v1.ListEventRegistrationsResponse\x12J\n" +
	"\vUpdateEvent\x12\x1c.buygo.v1.UpdateEventRequest\x1a\x1d.buygo.v1.UpdateEventResponse\x12\\\n" +
	"\x11UpdateEventStatus\x12\".buygo.v1.UpdateEventStatusRequest\x1a#.buygo.v1.UpdateEventStatusResponseB+Z)github.com/buygo/buygo-api/api/v1;buygov1b\x06proto3"

var (
	file_api_v1_event_proto_rawDescOnce sync.Once
	file_api_v1_event_proto_rawDescData []byte
)

func file_api_v1_event_proto_rawDescGZIP() []byte {
	file_api_v1_event_proto_rawDescOnce.Do(func() {
		file_api_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_event_proto_rawDesc), len(file_api_v1_event_proto_rawDesc)))
	})
	return file_api_v1_event_proto_rawDescData
}

var file_api_v1_event_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_api_v1_event_proto_goTypes = []any{
	(EventStatus)(0),                         // 0: buygo.v1.EventStatus
	(RegistrationStatus)(0),                  // 1: buygo.v1.RegistrationStatus
	(*UpdateRegistrationRequest)(nil),        // 2: buygo.v1.UpdateRegistrationRequest
	(*UpdateRegistrationResponse)(nil),       // 3: buygo.v1.UpdateRegistrationResponse
	(*UpdateRegistrationStatusRequest)(nil),  // 4: buygo.v1.UpdateRegistrationStatusRequest
	(*UpdateRegistrationStatusResponse)(nil), // 5: buygo.v1.UpdateRegistrationStatusResponse
	(*Event)(nil),                            // 6: buygo.v1.Event
	(*EventItem)(nil),                        // 7: buygo.v1.EventItem
	(*DiscountRule)(nil),                     // 8: buygo.v1.DiscountRule
	(*GetEventRequest)(nil),                  // 9: buygo.v1.GetEventRequest
	(*GetEventResponse)(nil),                 // 10: buygo.v1.GetEventResponse
	(*CreateEventRequest)(nil),               // 11: buygo.v1.CreateEventRequest
	(*CreateEventResponse)(nil),              // 12: buygo.v1.CreateEventResponse
	(*UpdateEventRequest)(nil),               // 13: buygo.v1.UpdateEventRequest
	(*UpdateEventResponse)(nil),              // 14: buygo.v1.UpdateEventResponse
	(*UpdateEventStatusRequest)(nil),         // 15: buygo.v1.UpdateEventStatusRequest
	(*UpdateEventStatusResponse)(nil),        // 16: buygo.v1.UpdateEventStatusResponse
	(*ListEventsRequest)(nil),                // 17: buygo.v1.ListEventsRequest
	(*ListEventsResponse)(nil),               // 18: buygo.v1.ListEventsResponse
	(*ListManagerEventsRequest)(nil),         // 19: buygo.v1.ListManagerEventsRequest
	(*ListManagerEventsResponse)(nil),        // 20: buygo.v1.ListManagerEventsResponse
	(*RegisterEventRequest)(nil),             // 21: buygo.v1.RegisterEventRequest
	(*RegisterItem)(nil),                     // 22: buygo.v1.RegisterItem
	(*RegisterEventResponse)(nil),            // 23: buygo.v1.RegisterEventResponse
	(*CancelRegistrationRequest)(nil),        // 24: buygo.v1.CancelRegistrationRequest
	(*CancelRegistrationResponse)(nil),       // 25: buygo.v1.CancelRegistrationResponse
	(*Registration)(nil),                     // 26: buygo.v1.Registration
	(*GetMyRegistrationsRequest)(nil),        // 27: buygo.v1.GetMyRegistrationsRequest
	(*GetMyRegistrationsResponse)(nil),       // 28: buygo.v1.GetMyRegistrationsResponse
	(*ListEventRegistrationsRequest)(nil),    // 29: buygo.v1.ListEventRegistrationsRequest
	(*ListEventRegistrationsResponse)(nil),   // 30: buygo.v1.ListEventRegistrationsResponse
	(PaymentStatus)(0),                       // 31: buygo.v1.PaymentStatus
	(*timestamppb.Timestamp)(nil),            // 32: google.protobuf.Timestamp
	(*User)(nil),                             // 33: buygo.v1.User
}
var file_api_v1_event_proto_depIdxs = []int32{
	22, // 0: buygo.v1.UpdateRegistrationRequest.items:type_name -> buygo.v1.RegisterItem
	1,  // 1: buygo.v1.UpdateRegistrationResponse.status:type_name -> buygo.v1.RegistrationStatus
	1,  // 2: buygo.v1.UpdateRegistrationStatusRequest.status:type_name -> buygo.v1.RegistrationStatus
	31, // 3: buygo.v1.UpdateRegistrationStatusRequest.payment_status:type_name -> buygo.v1.PaymentStatus
	1,  // 4: buygo.v1.UpdateRegistrationStatusResponse.status:type_name -> buygo.v1.RegistrationStatus
	31, // 5: buygo.v1.UpdateRegistrationStatusResponse.payment_status:type_name -> buygo.v1.PaymentStatus
	0,  // 6: buygo.v1.Event.status:type_name -> buygo.v1.EventStatus
	32, // 7: buygo.v1.Event.start_time:type_name -> google.protobuf.Timestamp
	32, // 8: buygo.v1.Event.end_time:type_name -> google.protobuf.Timestamp
	32, // 9: buygo.v1.Event.registration_deadline:type_name -> google.protobuf.Timestamp
	33, // 10: buygo.v1.Event.creator:type_name -> buygo.v1.User
	33, // 11: buygo.v1.Event.managers:type_name -> buygo.v1.User
	7,  // 12: buygo.v1.Event.items:type_name -> buygo.v1.EventItem
	8,  // 13: buygo.v1.Event.discounts:type_name -> buygo.v1.DiscountRule
	32, // 14: buygo.v1.EventItem.start_time:type_name -> google.protobuf.Timestamp
	32, // 15: buygo.v1.EventItem.end_time:type_name -> google.protobuf.Timestamp
	6,  // 16: buygo.v1.GetEventResponse.event:type_name -> buygo.v1.Event
	32, // 17: buygo.v1.CreateEventRequest.start_time:type_name -> google.protobuf.Timestamp
	32, // 18: buygo.v1.CreateEventRequest.end_time:type_name -> google.protobuf.Timestamp
	8,  // 19: buygo.v1.CreateEventRequest.discounts:type_name -> buygo.v1.DiscountRule
	7,  // 20: buygo.v1.CreateEventRequest.items:type_name -> buygo.v1.EventItem
	32, // 21: buygo.v1.CreateEventRequest.registration_deadline:type_name -> google.protobuf.Timestamp
	6,  // 22: buygo.v1.CreateEventResponse.event:type_name -> buygo.v1.Event
	32, // 23: buygo.v1.UpdateEventRequest.start_time:type_name -> google.protobuf.Timestamp
	32, // 24: buygo.v1.UpdateEventRequest.end_time:type_name -> google.protobuf.Timestamp
	7,  // 25: buygo.v1.UpdateEventRequest.items:type_name -> buygo.v1.EventItem
	8,  // 26: buygo.v1.UpdateEventRequest.discounts:type_name -> buygo.v1.DiscountRule
	6,  // 27: buygo.v1.UpdateEventResponse.event:type_name -> buygo.v1.Event
	0,  // 28: buygo.v1.UpdateEventStatusRequest.status:type_name -> buygo.v1.EventStatus
	6,  // 29: buygo.v1.UpdateEventStatusResponse.event:type_name -> buygo.v1.Event
	6,  // 30: buygo.v1.ListEventsResponse.events:type_name -> buygo.v1.Event
	6,  // 31: buygo.v1.ListManagerEventsResponse.events:type_name -> buygo.v1.Event
	22, // 32: buygo.v1.RegisterEventRequest.items:type_name -> buygo.v1.RegisterItem
	1,  // 33: buygo.v1.RegisterEventResponse.status:type_name -> buygo.v1.RegistrationStatus
	1,  // 34: buygo.v1.CancelRegistrationResponse.status:type_name -> buygo.v1.RegistrationStatus
	1,  // 35: buygo.v1.Registration.status:type_name -> buygo.v1.RegistrationStatus
	31, // 36: buygo.v1.Registration.payment_status:type_name -> buygo.v1.PaymentStatus
	22, // 37: buygo.v1.Registration.selected_items:type_name -> buygo.v1.RegisterItem
	33, // 38: buygo.v1.Registration.user:type_name -> buygo.v1.User
	26, // 39: buygo.v1.GetMyRegistrationsResponse.registrations:type_name -> buygo.v1.Registration
	26, // 40: buygo.v1.ListEventRegistrationsResponse.registrations:type_name -> buygo.v1.Registration
	11, // 41: buygo.v1.EventService.CreateEvent:input_type -> buygo.v1.CreateEventRequest
	17, // 42: buygo.v1.EventService.ListEvents:input_type -> buygo.v1.ListEventsRequest
	19, // 43: buygo.v1.EventService.ListManagerEvents:input_type -> buygo.v1.ListManagerEventsRequest
	9,  // 44: buygo.v1.EventService.GetEvent:input_type -> buygo.v1.GetEventRequest
	21, // 45: buygo.v1.EventService.RegisterEvent:input_type -> buygo.v1.RegisterEventRequest
	2,  // 46: buygo.v1.EventService.UpdateRegistration:input_type -> buygo.v1.UpdateRegistrationRequest
	4,  // 47: buygo.v1.EventService.UpdateRegistrationStatus:input_type -> buygo.v1.UpdateRegistrationStatusRequest
	24, // 48: buygo.v1.EventService.CancelRegistration:input_type -> buygo.v1.CancelRegistrationRequest
	27, // 49: buygo.v1.EventService.GetMyRegistrations:input_type -> buygo.v1.GetMyRegistrationsRequest
	29, // 50: buygo.v1.EventService.ListEventRegistrations:input_type -> buygo.v1.ListEventRegistrationsRequest
	13, // 51: buygo.v1.EventService.UpdateEvent:input_type -> buygo.v1.UpdateEventRequest
	15, // 52: buygo.v1.EventService.UpdateEventStatus:input_type -> buygo.v1.UpdateEventStatusRequest
	12, // 53: buygo.v1.EventService.CreateEvent:output_type -> buygo.v1.CreateEventResponse
	18, // 54: buygo.v1.EventService.ListEvents:output_type -> buygo.v1.ListEventsResponse
	20, // 55: buygo.v1.EventService.ListManagerEvents:output_type -> buygo.v1.ListManagerEventsResponse
	10, // 56: buygo.v1.EventService.GetEvent:output_type -> buygo.v1.GetEventResponse
	23, // 57: buygo.v1.EventService.RegisterEvent:output_type -> buygo.v1.RegisterEventResponse
	3,  // 58: buygo.v1.EventService.UpdateRegistration:output_type -> buygo.v1.UpdateRegistrationResponse
	5,  // 59: buygo.v1.EventService.UpdateRegistrationStatus:output_type -> buygo.v1.UpdateRegistrationStatusResponse
	25, // 60: buygo.v1.EventService.CancelRegistration:output_type -> buygo.v1.CancelRegistrationResponse
	28, // 61: buygo.v1.EventService.GetMyRegistrations:output_type -> buygo.v1.GetMyRegistrationsResponse
	30, // 62: buygo.v1.EventService.ListEventRegistrations:output_type -> buygo.v1.ListEventRegistrationsResponse
	14, // 63: buygo.v1.EventService.UpdateEvent:output_type -> buygo.v1.UpdateEventResponse
	16, // 64: buygo.v1.EventService.UpdateEventStatus:output_type -> buygo.v1.UpdateEventStatusResponse
	53, // [53:65] is the sub-list for method output_type
	41, // [41:53] is the sub-list for method input_type
	41, // [41:41] is the sub-list for extension type_name
	41, // [41:41] is the sub-list for extension extendee
	0,  // [0:41] is the sub-list for field type_name
}

func init() { file_api_v1_event_proto_init() }
func file_api_v1_event_proto_init() {
	if File_api_v1_event_proto != nil {
		return
	}
	file_api_v1_auth_proto_init()
	file_api_v1_groupbuy_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_event_proto_rawDesc), len(file_api_v1_event_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_event_proto_goTypes,
		DependencyIndexes: file_api_v1_event_proto_depIdxs,
		EnumInfos:         file_api_v1_event_proto_enumTypes,
		MessageInfos:      file_api_v1_event_proto_msgTypes,
	}.Build()
	File_api_v1_event_proto = out.File
	file_api_v1_event_proto_goTypes = nil
	file_api_v1_event_proto_depIdxs = nil
}
