// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/v1/auth.proto

package buygov1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/buygo/buygo-api/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "buygo.v1.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceLoginProcedure is the fully-qualified name of the AuthService's Login RPC.
	AuthServiceLoginProcedure = "/buygo.v1.AuthService/Login"
	// AuthServiceListUsersProcedure is the fully-qualified name of the AuthService's ListUsers RPC.
	AuthServiceListUsersProcedure = "/buygo.v1.AuthService/ListUsers"
	// AuthServiceUpdateUserRoleProcedure is the fully-qualified name of the AuthService's
	// UpdateUserRole RPC.
	AuthServiceUpdateUserRoleProcedure = "/buygo.v1.AuthService/UpdateUserRole"
	// AuthServiceGetMeProcedure is the fully-qualified name of the AuthService's GetMe RPC.
	AuthServiceGetMeProcedure = "/buygo.v1.AuthService/GetMe"
	// AuthServiceListAssignableManagersProcedure is the fully-qualified name of the AuthService's
	// ListAssignableManagers RPC.
	AuthServiceListAssignableManagersProcedure = "/buygo.v1.AuthService/ListAssignableManagers"
)

// AuthServiceClient is a client for the buygo.v1.AuthService service.
type AuthServiceClient interface {
	// Login with 3rd Party Token (Firebase)
	Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error)
	// Admin only: List users for management
	ListUsers(context.Context, *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error)
	// Admin only: Update user role
	UpdateUserRole(context.Context, *connect.Request[v1.UpdateUserRoleRequest]) (*connect.Response[v1.UpdateUserRoleResponse], error)
	// Get current user profile (Self)
	GetMe(context.Context, *connect.Request[v1.GetMeRequest]) (*connect.Response[v1.GetMeResponse], error)
	// List Users eligible to be Managers (Creator or SysAdmin)
	ListAssignableManagers(context.Context, *connect.Request[v1.ListAssignableManagersRequest]) (*connect.Response[v1.ListAssignableManagersResponse], error)
}

// NewAuthServiceClient constructs a client for the buygo.v1.AuthService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := v1.File_api_v1_auth_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		login: connect.NewClient[v1.LoginRequest, v1.LoginResponse](
			httpClient,
			baseURL+AuthServiceLoginProcedure,
			connect.WithSchema(authServiceMethods.ByName("Login")),
			connect.WithClientOptions(opts...),
		),
		listUsers: connect.NewClient[v1.ListUsersRequest, v1.ListUsersResponse](
			httpClient,
			baseURL+AuthServiceListUsersProcedure,
			connect.WithSchema(authServiceMethods.ByName("ListUsers")),
			connect.WithClientOptions(opts...),
		),
		updateUserRole: connect.NewClient[v1.UpdateUserRoleRequest, v1.UpdateUserRoleResponse](
			httpClient,
			baseURL+AuthServiceUpdateUserRoleProcedure,
			connect.WithSchema(authServiceMethods.ByName("UpdateUserRole")),
			connect.WithClientOptions(opts...),
		),
		getMe: connect.NewClient[v1.GetMeRequest, v1.GetMeResponse](
			httpClient,
			baseURL+AuthServiceGetMeProcedure,
			connect.WithSchema(authServiceMethods.ByName("GetMe")),
			connect.WithClientOptions(opts...),
		),
		listAssignableManagers: connect.NewClient[v1.ListAssignableManagersRequest, v1.ListAssignableManagersResponse](
			httpClient,
			baseURL+AuthServiceListAssignableManagersProcedure,
			connect.WithSchema(authServiceMethods.ByName("ListAssignableManagers")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	login                  *connect.Client[v1.LoginRequest, v1.LoginResponse]
	listUsers              *connect.Client[v1.ListUsersRequest, v1.ListUsersResponse]
	updateUserRole         *connect.Client[v1.UpdateUserRoleRequest, v1.UpdateUserRoleResponse]
	getMe                  *connect.Client[v1.GetMeRequest, v1.GetMeResponse]
	listAssignableManagers *connect.Client[v1.ListAssignableManagersRequest, v1.ListAssignableManagersResponse]
}

// Login calls buygo.v1.AuthService.Login.
func (c *authServiceClient) Login(ctx context.Context, req *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// ListUsers calls buygo.v1.AuthService.ListUsers.
func (c *authServiceClient) ListUsers(ctx context.Context, req *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error) {
	return c.listUsers.CallUnary(ctx, req)
}

// UpdateUserRole calls buygo.v1.AuthService.UpdateUserRole.
func (c *authServiceClient) UpdateUserRole(ctx context.Context, req *connect.Request[v1.UpdateUserRoleRequest]) (*connect.Response[v1.UpdateUserRoleResponse], error) {
	return c.updateUserRole.CallUnary(ctx, req)
}

// GetMe calls buygo.v1.AuthService.GetMe.
func (c *authServiceClient) GetMe(ctx context.Context, req *connect.Request[v1.GetMeRequest]) (*connect.Response[v1.GetMeResponse], error) {
	return c.getMe.CallUnary(ctx, req)
}

// ListAssignableManagers calls buygo.v1.AuthService.ListAssignableManagers.
func (c *authServiceClient) ListAssignableManagers(ctx context.Context, req *connect.Request[v1.ListAssignableManagersRequest]) (*connect.Response[v1.ListAssignableManagersResponse], error) {
	return c.listAssignableManagers.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the buygo.v1.AuthService service.
type AuthServiceHandler interface {
	// Login with 3rd Party Token (Firebase)
	Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error)
	// Admin only: List users for management
	ListUsers(context.Context, *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error)
	// Admin only: Update user role
	UpdateUserRole(context.Context, *connect.Request[v1.UpdateUserRoleRequest]) (*connect.Response[v1.UpdateUserRoleResponse], error)
	// Get current user profile (Self)
	GetMe(context.Context, *connect.Request[v1.GetMeRequest]) (*connect.Response[v1.GetMeResponse], error)
	// List Users eligible to be Managers (Creator or SysAdmin)
	ListAssignableManagers(context.Context, *connect.Request[v1.ListAssignableManagersRequest]) (*connect.Response[v1.ListAssignableManagersResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := v1.File_api_v1_auth_proto.Services().ByName("AuthService").Methods()
	authServiceLoginHandler := connect.NewUnaryHandler(
		AuthServiceLoginProcedure,
		svc.Login,
		connect.WithSchema(authServiceMethods.ByName("Login")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceListUsersHandler := connect.NewUnaryHandler(
		AuthServiceListUsersProcedure,
		svc.ListUsers,
		connect.WithSchema(authServiceMethods.ByName("ListUsers")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceUpdateUserRoleHandler := connect.NewUnaryHandler(
		AuthServiceUpdateUserRoleProcedure,
		svc.UpdateUserRole,
		connect.WithSchema(authServiceMethods.ByName("UpdateUserRole")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceGetMeHandler := connect.NewUnaryHandler(
		AuthServiceGetMeProcedure,
		svc.GetMe,
		connect.WithSchema(authServiceMethods.ByName("GetMe")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceListAssignableManagersHandler := connect.NewUnaryHandler(
		AuthServiceListAssignableManagersProcedure,
		svc.ListAssignableManagers,
		connect.WithSchema(authServiceMethods.ByName("ListAssignableManagers")),
		connect.WithHandlerOptions(opts...),
	)
	return "/buygo.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceLoginProcedure:
			authServiceLoginHandler.ServeHTTP(w, r)
		case AuthServiceListUsersProcedure:
			authServiceListUsersHandler.ServeHTTP(w, r)
		case AuthServiceUpdateUserRoleProcedure:
			authServiceUpdateUserRoleHandler.ServeHTTP(w, r)
		case AuthServiceGetMeProcedure:
			authServiceGetMeHandler.ServeHTTP(w, r)
		case AuthServiceListAssignableManagersProcedure:
			authServiceListAssignableManagersHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.AuthService.Login is not implemented"))
}

func (UnimplementedAuthServiceHandler) ListUsers(context.Context, *connect.Request[v1.ListUsersRequest]) (*connect.Response[v1.ListUsersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.AuthService.ListUsers is not implemented"))
}

func (UnimplementedAuthServiceHandler) UpdateUserRole(context.Context, *connect.Request[v1.UpdateUserRoleRequest]) (*connect.Response[v1.UpdateUserRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.AuthService.UpdateUserRole is not implemented"))
}

func (UnimplementedAuthServiceHandler) GetMe(context.Context, *connect.Request[v1.GetMeRequest]) (*connect.Response[v1.GetMeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.AuthService.GetMe is not implemented"))
}

func (UnimplementedAuthServiceHandler) ListAssignableManagers(context.Context, *connect.Request[v1.ListAssignableManagersRequest]) (*connect.Response[v1.ListAssignableManagersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.AuthService.ListAssignableManagers is not implemented"))
}
