// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/v1/event.proto

package buygov1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/buygo/buygo-api/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EventServiceName is the fully-qualified name of the EventService service.
	EventServiceName = "buygo.v1.EventService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EventServiceCreateEventProcedure is the fully-qualified name of the EventService's CreateEvent
	// RPC.
	EventServiceCreateEventProcedure = "/buygo.v1.EventService/CreateEvent"
	// EventServiceListEventsProcedure is the fully-qualified name of the EventService's ListEvents RPC.
	EventServiceListEventsProcedure = "/buygo.v1.EventService/ListEvents"
	// EventServiceListManagerEventsProcedure is the fully-qualified name of the EventService's
	// ListManagerEvents RPC.
	EventServiceListManagerEventsProcedure = "/buygo.v1.EventService/ListManagerEvents"
	// EventServiceGetEventProcedure is the fully-qualified name of the EventService's GetEvent RPC.
	EventServiceGetEventProcedure = "/buygo.v1.EventService/GetEvent"
	// EventServiceRegisterEventProcedure is the fully-qualified name of the EventService's
	// RegisterEvent RPC.
	EventServiceRegisterEventProcedure = "/buygo.v1.EventService/RegisterEvent"
	// EventServiceUpdateRegistrationProcedure is the fully-qualified name of the EventService's
	// UpdateRegistration RPC.
	EventServiceUpdateRegistrationProcedure = "/buygo.v1.EventService/UpdateRegistration"
	// EventServiceUpdateRegistrationStatusProcedure is the fully-qualified name of the EventService's
	// UpdateRegistrationStatus RPC.
	EventServiceUpdateRegistrationStatusProcedure = "/buygo.v1.EventService/UpdateRegistrationStatus"
	// EventServiceCancelRegistrationProcedure is the fully-qualified name of the EventService's
	// CancelRegistration RPC.
	EventServiceCancelRegistrationProcedure = "/buygo.v1.EventService/CancelRegistration"
	// EventServiceGetMyRegistrationsProcedure is the fully-qualified name of the EventService's
	// GetMyRegistrations RPC.
	EventServiceGetMyRegistrationsProcedure = "/buygo.v1.EventService/GetMyRegistrations"
	// EventServiceListEventRegistrationsProcedure is the fully-qualified name of the EventService's
	// ListEventRegistrations RPC.
	EventServiceListEventRegistrationsProcedure = "/buygo.v1.EventService/ListEventRegistrations"
	// EventServiceUpdateEventProcedure is the fully-qualified name of the EventService's UpdateEvent
	// RPC.
	EventServiceUpdateEventProcedure = "/buygo.v1.EventService/UpdateEvent"
	// EventServiceUpdateEventStatusProcedure is the fully-qualified name of the EventService's
	// UpdateEventStatus RPC.
	EventServiceUpdateEventStatusProcedure = "/buygo.v1.EventService/UpdateEventStatus"
)

// EventServiceClient is a client for the buygo.v1.EventService service.
type EventServiceClient interface {
	CreateEvent(context.Context, *connect.Request[v1.CreateEventRequest]) (*connect.Response[v1.CreateEventResponse], error)
	ListEvents(context.Context, *connect.Request[v1.ListEventsRequest]) (*connect.Response[v1.ListEventsResponse], error)
	ListManagerEvents(context.Context, *connect.Request[v1.ListManagerEventsRequest]) (*connect.Response[v1.ListManagerEventsResponse], error)
	GetEvent(context.Context, *connect.Request[v1.GetEventRequest]) (*connect.Response[v1.GetEventResponse], error)
	// Registration
	RegisterEvent(context.Context, *connect.Request[v1.RegisterEventRequest]) (*connect.Response[v1.RegisterEventResponse], error)
	UpdateRegistration(context.Context, *connect.Request[v1.UpdateRegistrationRequest]) (*connect.Response[v1.UpdateRegistrationResponse], error)
	UpdateRegistrationStatus(context.Context, *connect.Request[v1.UpdateRegistrationStatusRequest]) (*connect.Response[v1.UpdateRegistrationStatusResponse], error)
	CancelRegistration(context.Context, *connect.Request[v1.CancelRegistrationRequest]) (*connect.Response[v1.CancelRegistrationResponse], error)
	GetMyRegistrations(context.Context, *connect.Request[v1.GetMyRegistrationsRequest]) (*connect.Response[v1.GetMyRegistrationsResponse], error)
	ListEventRegistrations(context.Context, *connect.Request[v1.ListEventRegistrationsRequest]) (*connect.Response[v1.ListEventRegistrationsResponse], error)
	// Management
	UpdateEvent(context.Context, *connect.Request[v1.UpdateEventRequest]) (*connect.Response[v1.UpdateEventResponse], error)
	UpdateEventStatus(context.Context, *connect.Request[v1.UpdateEventStatusRequest]) (*connect.Response[v1.UpdateEventStatusResponse], error)
}

// NewEventServiceClient constructs a client for the buygo.v1.EventService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEventServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EventServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	eventServiceMethods := v1.File_api_v1_event_proto.Services().ByName("EventService").Methods()
	return &eventServiceClient{
		createEvent: connect.NewClient[v1.CreateEventRequest, v1.CreateEventResponse](
			httpClient,
			baseURL+EventServiceCreateEventProcedure,
			connect.WithSchema(eventServiceMethods.ByName("CreateEvent")),
			connect.WithClientOptions(opts...),
		),
		listEvents: connect.NewClient[v1.ListEventsRequest, v1.ListEventsResponse](
			httpClient,
			baseURL+EventServiceListEventsProcedure,
			connect.WithSchema(eventServiceMethods.ByName("ListEvents")),
			connect.WithClientOptions(opts...),
		),
		listManagerEvents: connect.NewClient[v1.ListManagerEventsRequest, v1.ListManagerEventsResponse](
			httpClient,
			baseURL+EventServiceListManagerEventsProcedure,
			connect.WithSchema(eventServiceMethods.ByName("ListManagerEvents")),
			connect.WithClientOptions(opts...),
		),
		getEvent: connect.NewClient[v1.GetEventRequest, v1.GetEventResponse](
			httpClient,
			baseURL+EventServiceGetEventProcedure,
			connect.WithSchema(eventServiceMethods.ByName("GetEvent")),
			connect.WithClientOptions(opts...),
		),
		registerEvent: connect.NewClient[v1.RegisterEventRequest, v1.RegisterEventResponse](
			httpClient,
			baseURL+EventServiceRegisterEventProcedure,
			connect.WithSchema(eventServiceMethods.ByName("RegisterEvent")),
			connect.WithClientOptions(opts...),
		),
		updateRegistration: connect.NewClient[v1.UpdateRegistrationRequest, v1.UpdateRegistrationResponse](
			httpClient,
			baseURL+EventServiceUpdateRegistrationProcedure,
			connect.WithSchema(eventServiceMethods.ByName("UpdateRegistration")),
			connect.WithClientOptions(opts...),
		),
		updateRegistrationStatus: connect.NewClient[v1.UpdateRegistrationStatusRequest, v1.UpdateRegistrationStatusResponse](
			httpClient,
			baseURL+EventServiceUpdateRegistrationStatusProcedure,
			connect.WithSchema(eventServiceMethods.ByName("UpdateRegistrationStatus")),
			connect.WithClientOptions(opts...),
		),
		cancelRegistration: connect.NewClient[v1.CancelRegistrationRequest, v1.CancelRegistrationResponse](
			httpClient,
			baseURL+EventServiceCancelRegistrationProcedure,
			connect.WithSchema(eventServiceMethods.ByName("CancelRegistration")),
			connect.WithClientOptions(opts...),
		),
		getMyRegistrations: connect.NewClient[v1.GetMyRegistrationsRequest, v1.GetMyRegistrationsResponse](
			httpClient,
			baseURL+EventServiceGetMyRegistrationsProcedure,
			connect.WithSchema(eventServiceMethods.ByName("GetMyRegistrations")),
			connect.WithClientOptions(opts...),
		),
		listEventRegistrations: connect.NewClient[v1.ListEventRegistrationsRequest, v1.ListEventRegistrationsResponse](
			httpClient,
			baseURL+EventServiceListEventRegistrationsProcedure,
			connect.WithSchema(eventServiceMethods.ByName("ListEventRegistrations")),
			connect.WithClientOptions(opts...),
		),
		updateEvent: connect.NewClient[v1.UpdateEventRequest, v1.UpdateEventResponse](
			httpClient,
			baseURL+EventServiceUpdateEventProcedure,
			connect.WithSchema(eventServiceMethods.ByName("UpdateEvent")),
			connect.WithClientOptions(opts...),
		),
		updateEventStatus: connect.NewClient[v1.UpdateEventStatusRequest, v1.UpdateEventStatusResponse](
			httpClient,
			baseURL+EventServiceUpdateEventStatusProcedure,
			connect.WithSchema(eventServiceMethods.ByName("UpdateEventStatus")),
			connect.WithClientOptions(opts...),
		),
	}
}

// eventServiceClient implements EventServiceClient.
type eventServiceClient struct {
	createEvent              *connect.Client[v1.CreateEventRequest, v1.CreateEventResponse]
	listEvents               *connect.Client[v1.ListEventsRequest, v1.ListEventsResponse]
	listManagerEvents        *connect.Client[v1.ListManagerEventsRequest, v1.ListManagerEventsResponse]
	getEvent                 *connect.Client[v1.GetEventRequest, v1.GetEventResponse]
	registerEvent            *connect.Client[v1.RegisterEventRequest, v1.RegisterEventResponse]
	updateRegistration       *connect.Client[v1.UpdateRegistrationRequest, v1.UpdateRegistrationResponse]
	updateRegistrationStatus *connect.Client[v1.UpdateRegistrationStatusRequest, v1.UpdateRegistrationStatusResponse]
	cancelRegistration       *connect.Client[v1.CancelRegistrationRequest, v1.CancelRegistrationResponse]
	getMyRegistrations       *connect.Client[v1.GetMyRegistrationsRequest, v1.GetMyRegistrationsResponse]
	listEventRegistrations   *connect.Client[v1.ListEventRegistrationsRequest, v1.ListEventRegistrationsResponse]
	updateEvent              *connect.Client[v1.UpdateEventRequest, v1.UpdateEventResponse]
	updateEventStatus        *connect.Client[v1.UpdateEventStatusRequest, v1.UpdateEventStatusResponse]
}

// CreateEvent calls buygo.v1.EventService.CreateEvent.
func (c *eventServiceClient) CreateEvent(ctx context.Context, req *connect.Request[v1.CreateEventRequest]) (*connect.Response[v1.CreateEventResponse], error) {
	return c.createEvent.CallUnary(ctx, req)
}

// ListEvents calls buygo.v1.EventService.ListEvents.
func (c *eventServiceClient) ListEvents(ctx context.Context, req *connect.Request[v1.ListEventsRequest]) (*connect.Response[v1.ListEventsResponse], error) {
	return c.listEvents.CallUnary(ctx, req)
}

// ListManagerEvents calls buygo.v1.EventService.ListManagerEvents.
func (c *eventServiceClient) ListManagerEvents(ctx context.Context, req *connect.Request[v1.ListManagerEventsRequest]) (*connect.Response[v1.ListManagerEventsResponse], error) {
	return c.listManagerEvents.CallUnary(ctx, req)
}

// GetEvent calls buygo.v1.EventService.GetEvent.
func (c *eventServiceClient) GetEvent(ctx context.Context, req *connect.Request[v1.GetEventRequest]) (*connect.Response[v1.GetEventResponse], error) {
	return c.getEvent.CallUnary(ctx, req)
}

// RegisterEvent calls buygo.v1.EventService.RegisterEvent.
func (c *eventServiceClient) RegisterEvent(ctx context.Context, req *connect.Request[v1.RegisterEventRequest]) (*connect.Response[v1.RegisterEventResponse], error) {
	return c.registerEvent.CallUnary(ctx, req)
}

// UpdateRegistration calls buygo.v1.EventService.UpdateRegistration.
func (c *eventServiceClient) UpdateRegistration(ctx context.Context, req *connect.Request[v1.UpdateRegistrationRequest]) (*connect.Response[v1.UpdateRegistrationResponse], error) {
	return c.updateRegistration.CallUnary(ctx, req)
}

// UpdateRegistrationStatus calls buygo.v1.EventService.UpdateRegistrationStatus.
func (c *eventServiceClient) UpdateRegistrationStatus(ctx context.Context, req *connect.Request[v1.UpdateRegistrationStatusRequest]) (*connect.Response[v1.UpdateRegistrationStatusResponse], error) {
	return c.updateRegistrationStatus.CallUnary(ctx, req)
}

// CancelRegistration calls buygo.v1.EventService.CancelRegistration.
func (c *eventServiceClient) CancelRegistration(ctx context.Context, req *connect.Request[v1.CancelRegistrationRequest]) (*connect.Response[v1.CancelRegistrationResponse], error) {
	return c.cancelRegistration.CallUnary(ctx, req)
}

// GetMyRegistrations calls buygo.v1.EventService.GetMyRegistrations.
func (c *eventServiceClient) GetMyRegistrations(ctx context.Context, req *connect.Request[v1.GetMyRegistrationsRequest]) (*connect.Response[v1.GetMyRegistrationsResponse], error) {
	return c.getMyRegistrations.CallUnary(ctx, req)
}

// ListEventRegistrations calls buygo.v1.EventService.ListEventRegistrations.
func (c *eventServiceClient) ListEventRegistrations(ctx context.Context, req *connect.Request[v1.ListEventRegistrationsRequest]) (*connect.Response[v1.ListEventRegistrationsResponse], error) {
	return c.listEventRegistrations.CallUnary(ctx, req)
}

// UpdateEvent calls buygo.v1.EventService.UpdateEvent.
func (c *eventServiceClient) UpdateEvent(ctx context.Context, req *connect.Request[v1.UpdateEventRequest]) (*connect.Response[v1.UpdateEventResponse], error) {
	return c.updateEvent.CallUnary(ctx, req)
}

// UpdateEventStatus calls buygo.v1.EventService.UpdateEventStatus.
func (c *eventServiceClient) UpdateEventStatus(ctx context.Context, req *connect.Request[v1.UpdateEventStatusRequest]) (*connect.Response[v1.UpdateEventStatusResponse], error) {
	return c.updateEventStatus.CallUnary(ctx, req)
}

// EventServiceHandler is an implementation of the buygo.v1.EventService service.
type EventServiceHandler interface {
	CreateEvent(context.Context, *connect.Request[v1.CreateEventRequest]) (*connect.Response[v1.CreateEventResponse], error)
	ListEvents(context.Context, *connect.Request[v1.ListEventsRequest]) (*connect.Response[v1.ListEventsResponse], error)
	ListManagerEvents(context.Context, *connect.Request[v1.ListManagerEventsRequest]) (*connect.Response[v1.ListManagerEventsResponse], error)
	GetEvent(context.Context, *connect.Request[v1.GetEventRequest]) (*connect.Response[v1.GetEventResponse], error)
	// Registration
	RegisterEvent(context.Context, *connect.Request[v1.RegisterEventRequest]) (*connect.Response[v1.RegisterEventResponse], error)
	UpdateRegistration(context.Context, *connect.Request[v1.UpdateRegistrationRequest]) (*connect.Response[v1.UpdateRegistrationResponse], error)
	UpdateRegistrationStatus(context.Context, *connect.Request[v1.UpdateRegistrationStatusRequest]) (*connect.Response[v1.UpdateRegistrationStatusResponse], error)
	CancelRegistration(context.Context, *connect.Request[v1.CancelRegistrationRequest]) (*connect.Response[v1.CancelRegistrationResponse], error)
	GetMyRegistrations(context.Context, *connect.Request[v1.GetMyRegistrationsRequest]) (*connect.Response[v1.GetMyRegistrationsResponse], error)
	ListEventRegistrations(context.Context, *connect.Request[v1.ListEventRegistrationsRequest]) (*connect.Response[v1.ListEventRegistrationsResponse], error)
	// Management
	UpdateEvent(context.Context, *connect.Request[v1.UpdateEventRequest]) (*connect.Response[v1.UpdateEventResponse], error)
	UpdateEventStatus(context.Context, *connect.Request[v1.UpdateEventStatusRequest]) (*connect.Response[v1.UpdateEventStatusResponse], error)
}

// NewEventServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEventServiceHandler(svc EventServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	eventServiceMethods := v1.File_api_v1_event_proto.Services().ByName("EventService").Methods()
	eventServiceCreateEventHandler := connect.NewUnaryHandler(
		EventServiceCreateEventProcedure,
		svc.CreateEvent,
		connect.WithSchema(eventServiceMethods.ByName("CreateEvent")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceListEventsHandler := connect.NewUnaryHandler(
		EventServiceListEventsProcedure,
		svc.ListEvents,
		connect.WithSchema(eventServiceMethods.ByName("ListEvents")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceListManagerEventsHandler := connect.NewUnaryHandler(
		EventServiceListManagerEventsProcedure,
		svc.ListManagerEvents,
		connect.WithSchema(eventServiceMethods.ByName("ListManagerEvents")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceGetEventHandler := connect.NewUnaryHandler(
		EventServiceGetEventProcedure,
		svc.GetEvent,
		connect.WithSchema(eventServiceMethods.ByName("GetEvent")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceRegisterEventHandler := connect.NewUnaryHandler(
		EventServiceRegisterEventProcedure,
		svc.RegisterEvent,
		connect.WithSchema(eventServiceMethods.ByName("RegisterEvent")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceUpdateRegistrationHandler := connect.NewUnaryHandler(
		EventServiceUpdateRegistrationProcedure,
		svc.UpdateRegistration,
		connect.WithSchema(eventServiceMethods.ByName("UpdateRegistration")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceUpdateRegistrationStatusHandler := connect.NewUnaryHandler(
		EventServiceUpdateRegistrationStatusProcedure,
		svc.UpdateRegistrationStatus,
		connect.WithSchema(eventServiceMethods.ByName("UpdateRegistrationStatus")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceCancelRegistrationHandler := connect.NewUnaryHandler(
		EventServiceCancelRegistrationProcedure,
		svc.CancelRegistration,
		connect.WithSchema(eventServiceMethods.ByName("CancelRegistration")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceGetMyRegistrationsHandler := connect.NewUnaryHandler(
		EventServiceGetMyRegistrationsProcedure,
		svc.GetMyRegistrations,
		connect.WithSchema(eventServiceMethods.ByName("GetMyRegistrations")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceListEventRegistrationsHandler := connect.NewUnaryHandler(
		EventServiceListEventRegistrationsProcedure,
		svc.ListEventRegistrations,
		connect.WithSchema(eventServiceMethods.ByName("ListEventRegistrations")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceUpdateEventHandler := connect.NewUnaryHandler(
		EventServiceUpdateEventProcedure,
		svc.UpdateEvent,
		connect.WithSchema(eventServiceMethods.ByName("UpdateEvent")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceUpdateEventStatusHandler := connect.NewUnaryHandler(
		EventServiceUpdateEventStatusProcedure,
		svc.UpdateEventStatus,
		connect.WithSchema(eventServiceMethods.ByName("UpdateEventStatus")),
		connect.WithHandlerOptions(opts...),
	)
	return "/buygo.v1.EventService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EventServiceCreateEventProcedure:
			eventServiceCreateEventHandler.ServeHTTP(w, r)
		case EventServiceListEventsProcedure:
			eventServiceListEventsHandler.ServeHTTP(w, r)
		case EventServiceListManagerEventsProcedure:
			eventServiceListManagerEventsHandler.ServeHTTP(w, r)
		case EventServiceGetEventProcedure:
			eventServiceGetEventHandler.ServeHTTP(w, r)
		case EventServiceRegisterEventProcedure:
			eventServiceRegisterEventHandler.ServeHTTP(w, r)
		case EventServiceUpdateRegistrationProcedure:
			eventServiceUpdateRegistrationHandler.ServeHTTP(w, r)
		case EventServiceUpdateRegistrationStatusProcedure:
			eventServiceUpdateRegistrationStatusHandler.ServeHTTP(w, r)
		case EventServiceCancelRegistrationProcedure:
			eventServiceCancelRegistrationHandler.ServeHTTP(w, r)
		case EventServiceGetMyRegistrationsProcedure:
			eventServiceGetMyRegistrationsHandler.ServeHTTP(w, r)
		case EventServiceListEventRegistrationsProcedure:
			eventServiceListEventRegistrationsHandler.ServeHTTP(w, r)
		case EventServiceUpdateEventProcedure:
			eventServiceUpdateEventHandler.ServeHTTP(w, r)
		case EventServiceUpdateEventStatusProcedure:
			eventServiceUpdateEventStatusHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEventServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEventServiceHandler struct{}

func (UnimplementedEventServiceHandler) CreateEvent(context.Context, *connect.Request[v1.CreateEventRequest]) (*connect.Response[v1.CreateEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.EventService.CreateEvent is not implemented"))
}

func (UnimplementedEventServiceHandler) ListEvents(context.Context, *connect.Request[v1.ListEventsRequest]) (*connect.Response[v1.ListEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.EventService.ListEvents is not implemented"))
}

func (UnimplementedEventServiceHandler) ListManagerEvents(context.Context, *connect.Request[v1.ListManagerEventsRequest]) (*connect.Response[v1.ListManagerEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.EventService.ListManagerEvents is not implemented"))
}

func (UnimplementedEventServiceHandler) GetEvent(context.Context, *connect.Request[v1.GetEventRequest]) (*connect.Response[v1.GetEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.EventService.GetEvent is not implemented"))
}

func (UnimplementedEventServiceHandler) RegisterEvent(context.Context, *connect.Request[v1.RegisterEventRequest]) (*connect.Response[v1.RegisterEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.EventService.RegisterEvent is not implemented"))
}

func (UnimplementedEventServiceHandler) UpdateRegistration(context.Context, *connect.Request[v1.UpdateRegistrationRequest]) (*connect.Response[v1.UpdateRegistrationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.EventService.UpdateRegistration is not implemented"))
}

func (UnimplementedEventServiceHandler) UpdateRegistrationStatus(context.Context, *connect.Request[v1.UpdateRegistrationStatusRequest]) (*connect.Response[v1.UpdateRegistrationStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.EventService.UpdateRegistrationStatus is not implemented"))
}

func (UnimplementedEventServiceHandler) CancelRegistration(context.Context, *connect.Request[v1.CancelRegistrationRequest]) (*connect.Response[v1.CancelRegistrationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.EventService.CancelRegistration is not implemented"))
}

func (UnimplementedEventServiceHandler) GetMyRegistrations(context.Context, *connect.Request[v1.GetMyRegistrationsRequest]) (*connect.Response[v1.GetMyRegistrationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.EventService.GetMyRegistrations is not implemented"))
}

func (UnimplementedEventServiceHandler) ListEventRegistrations(context.Context, *connect.Request[v1.ListEventRegistrationsRequest]) (*connect.Response[v1.ListEventRegistrationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.EventService.ListEventRegistrations is not implemented"))
}

func (UnimplementedEventServiceHandler) UpdateEvent(context.Context, *connect.Request[v1.UpdateEventRequest]) (*connect.Response[v1.UpdateEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.EventService.UpdateEvent is not implemented"))
}

func (UnimplementedEventServiceHandler) UpdateEventStatus(context.Context, *connect.Request[v1.UpdateEventStatusRequest]) (*connect.Response[v1.UpdateEventStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.EventService.UpdateEventStatus is not implemented"))
}
