// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/v1/groupbuy.proto

package buygov1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/hatsubosi/buygo-api/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GroupBuyServiceName is the fully-qualified name of the GroupBuyService service.
	GroupBuyServiceName = "buygo.v1.GroupBuyService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GroupBuyServiceCreateGroupBuyProcedure is the fully-qualified name of the GroupBuyService's
	// CreateGroupBuy RPC.
	GroupBuyServiceCreateGroupBuyProcedure = "/buygo.v1.GroupBuyService/CreateGroupBuy"
	// GroupBuyServiceListGroupBuysProcedure is the fully-qualified name of the GroupBuyService's
	// ListGroupBuys RPC.
	GroupBuyServiceListGroupBuysProcedure = "/buygo.v1.GroupBuyService/ListGroupBuys"
	// GroupBuyServiceListManagerGroupBuysProcedure is the fully-qualified name of the GroupBuyService's
	// ListManagerGroupBuys RPC.
	GroupBuyServiceListManagerGroupBuysProcedure = "/buygo.v1.GroupBuyService/ListManagerGroupBuys"
	// GroupBuyServiceGetGroupBuyProcedure is the fully-qualified name of the GroupBuyService's
	// GetGroupBuy RPC.
	GroupBuyServiceGetGroupBuyProcedure = "/buygo.v1.GroupBuyService/GetGroupBuy"
	// GroupBuyServiceUpdateGroupBuyProcedure is the fully-qualified name of the GroupBuyService's
	// UpdateGroupBuy RPC.
	GroupBuyServiceUpdateGroupBuyProcedure = "/buygo.v1.GroupBuyService/UpdateGroupBuy"
	// GroupBuyServiceAddProductProcedure is the fully-qualified name of the GroupBuyService's
	// AddProduct RPC.
	GroupBuyServiceAddProductProcedure = "/buygo.v1.GroupBuyService/AddProduct"
	// GroupBuyServiceCreateCategoryProcedure is the fully-qualified name of the GroupBuyService's
	// CreateCategory RPC.
	GroupBuyServiceCreateCategoryProcedure = "/buygo.v1.GroupBuyService/CreateCategory"
	// GroupBuyServiceListCategoriesProcedure is the fully-qualified name of the GroupBuyService's
	// ListCategories RPC.
	GroupBuyServiceListCategoriesProcedure = "/buygo.v1.GroupBuyService/ListCategories"
	// GroupBuyServiceCreateOrderProcedure is the fully-qualified name of the GroupBuyService's
	// CreateOrder RPC.
	GroupBuyServiceCreateOrderProcedure = "/buygo.v1.GroupBuyService/CreateOrder"
	// GroupBuyServiceCancelOrderProcedure is the fully-qualified name of the GroupBuyService's
	// CancelOrder RPC.
	GroupBuyServiceCancelOrderProcedure = "/buygo.v1.GroupBuyService/CancelOrder"
	// GroupBuyServiceGetMyGroupBuyOrderProcedure is the fully-qualified name of the GroupBuyService's
	// GetMyGroupBuyOrder RPC.
	GroupBuyServiceGetMyGroupBuyOrderProcedure = "/buygo.v1.GroupBuyService/GetMyGroupBuyOrder"
	// GroupBuyServiceUpdateOrderProcedure is the fully-qualified name of the GroupBuyService's
	// UpdateOrder RPC.
	GroupBuyServiceUpdateOrderProcedure = "/buygo.v1.GroupBuyService/UpdateOrder"
	// GroupBuyServiceUpdatePaymentInfoProcedure is the fully-qualified name of the GroupBuyService's
	// UpdatePaymentInfo RPC.
	GroupBuyServiceUpdatePaymentInfoProcedure = "/buygo.v1.GroupBuyService/UpdatePaymentInfo"
	// GroupBuyServiceGetMyOrdersProcedure is the fully-qualified name of the GroupBuyService's
	// GetMyOrders RPC.
	GroupBuyServiceGetMyOrdersProcedure = "/buygo.v1.GroupBuyService/GetMyOrders"
	// GroupBuyServiceBatchUpdateStatusProcedure is the fully-qualified name of the GroupBuyService's
	// BatchUpdateStatus RPC.
	GroupBuyServiceBatchUpdateStatusProcedure = "/buygo.v1.GroupBuyService/BatchUpdateStatus"
	// GroupBuyServiceConfirmPaymentProcedure is the fully-qualified name of the GroupBuyService's
	// ConfirmPayment RPC.
	GroupBuyServiceConfirmPaymentProcedure = "/buygo.v1.GroupBuyService/ConfirmPayment"
	// GroupBuyServiceListGroupBuyOrdersProcedure is the fully-qualified name of the GroupBuyService's
	// ListGroupBuyOrders RPC.
	GroupBuyServiceListGroupBuyOrdersProcedure = "/buygo.v1.GroupBuyService/ListGroupBuyOrders"
	// GroupBuyServiceCreatePriceTemplateProcedure is the fully-qualified name of the GroupBuyService's
	// CreatePriceTemplate RPC.
	GroupBuyServiceCreatePriceTemplateProcedure = "/buygo.v1.GroupBuyService/CreatePriceTemplate"
	// GroupBuyServiceListPriceTemplatesProcedure is the fully-qualified name of the GroupBuyService's
	// ListPriceTemplates RPC.
	GroupBuyServiceListPriceTemplatesProcedure = "/buygo.v1.GroupBuyService/ListPriceTemplates"
	// GroupBuyServiceGetPriceTemplateProcedure is the fully-qualified name of the GroupBuyService's
	// GetPriceTemplate RPC.
	GroupBuyServiceGetPriceTemplateProcedure = "/buygo.v1.GroupBuyService/GetPriceTemplate"
	// GroupBuyServiceUpdatePriceTemplateProcedure is the fully-qualified name of the GroupBuyService's
	// UpdatePriceTemplate RPC.
	GroupBuyServiceUpdatePriceTemplateProcedure = "/buygo.v1.GroupBuyService/UpdatePriceTemplate"
	// GroupBuyServiceDeletePriceTemplateProcedure is the fully-qualified name of the GroupBuyService's
	// DeletePriceTemplate RPC.
	GroupBuyServiceDeletePriceTemplateProcedure = "/buygo.v1.GroupBuyService/DeletePriceTemplate"
)

// GroupBuyServiceClient is a client for the buygo.v1.GroupBuyService service.
type GroupBuyServiceClient interface {
	// GroupBuy Management (Creator/Admin)
	CreateGroupBuy(context.Context, *connect.Request[v1.CreateGroupBuyRequest]) (*connect.Response[v1.CreateGroupBuyResponse], error)
	ListGroupBuys(context.Context, *connect.Request[v1.ListGroupBuysRequest]) (*connect.Response[v1.ListGroupBuysResponse], error)
	ListManagerGroupBuys(context.Context, *connect.Request[v1.ListManagerGroupBuysRequest]) (*connect.Response[v1.ListManagerGroupBuysResponse], error)
	GetGroupBuy(context.Context, *connect.Request[v1.GetGroupBuyRequest]) (*connect.Response[v1.GetGroupBuyResponse], error)
	UpdateGroupBuy(context.Context, *connect.Request[v1.UpdateGroupBuyRequest]) (*connect.Response[v1.UpdateGroupBuyResponse], error)
	// Product Management (Creator/Admin)
	AddProduct(context.Context, *connect.Request[v1.AddProductRequest]) (*connect.Response[v1.AddProductResponse], error)
	// Category (Template) Methods
	CreateCategory(context.Context, *connect.Request[v1.CreateCategoryRequest]) (*connect.Response[v1.CreateCategoryResponse], error)
	ListCategories(context.Context, *connect.Request[v1.ListCategoriesRequest]) (*connect.Response[v1.ListCategoriesResponse], error)
	// Order Management (User)
	CreateOrder(context.Context, *connect.Request[v1.CreateOrderRequest]) (*connect.Response[v1.CreateOrderResponse], error)
	CancelOrder(context.Context, *connect.Request[v1.CancelOrderRequest]) (*connect.Response[v1.CancelOrderResponse], error)
	GetMyGroupBuyOrder(context.Context, *connect.Request[v1.GetMyGroupBuyOrderRequest]) (*connect.Response[v1.GetMyGroupBuyOrderResponse], error)
	UpdateOrder(context.Context, *connect.Request[v1.UpdateOrderRequest]) (*connect.Response[v1.UpdateOrderResponse], error)
	UpdatePaymentInfo(context.Context, *connect.Request[v1.UpdatePaymentInfoRequest]) (*connect.Response[v1.UpdatePaymentInfoResponse], error)
	GetMyOrders(context.Context, *connect.Request[v1.GetMyOrdersRequest]) (*connect.Response[v1.GetMyOrdersResponse], error)
	// Order Management (Manager)
	// Batch update status of items (FIFO)
	BatchUpdateStatus(context.Context, *connect.Request[v1.BatchUpdateStatusRequest]) (*connect.Response[v1.BatchUpdateStatusResponse], error)
	// Confirm user payment
	// Confirm user payment
	ConfirmPayment(context.Context, *connect.Request[v1.ConfirmPaymentRequest]) (*connect.Response[v1.ConfirmPaymentResponse], error)
	// Manager: List Orders for a GroupBuy
	ListGroupBuyOrders(context.Context, *connect.Request[v1.ListGroupBuyOrdersRequest]) (*connect.Response[v1.ListGroupBuyOrdersResponse], error)
	// Price Templates (Admin Only)
	CreatePriceTemplate(context.Context, *connect.Request[v1.CreatePriceTemplateRequest]) (*connect.Response[v1.CreatePriceTemplateResponse], error)
	ListPriceTemplates(context.Context, *connect.Request[v1.ListPriceTemplatesRequest]) (*connect.Response[v1.ListPriceTemplatesResponse], error)
	GetPriceTemplate(context.Context, *connect.Request[v1.GetPriceTemplateRequest]) (*connect.Response[v1.GetPriceTemplateResponse], error)
	UpdatePriceTemplate(context.Context, *connect.Request[v1.UpdatePriceTemplateRequest]) (*connect.Response[v1.UpdatePriceTemplateResponse], error)
	DeletePriceTemplate(context.Context, *connect.Request[v1.DeletePriceTemplateRequest]) (*connect.Response[v1.DeletePriceTemplateResponse], error)
}

// NewGroupBuyServiceClient constructs a client for the buygo.v1.GroupBuyService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGroupBuyServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GroupBuyServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	groupBuyServiceMethods := v1.File_api_v1_groupbuy_proto.Services().ByName("GroupBuyService").Methods()
	return &groupBuyServiceClient{
		createGroupBuy: connect.NewClient[v1.CreateGroupBuyRequest, v1.CreateGroupBuyResponse](
			httpClient,
			baseURL+GroupBuyServiceCreateGroupBuyProcedure,
			connect.WithSchema(groupBuyServiceMethods.ByName("CreateGroupBuy")),
			connect.WithClientOptions(opts...),
		),
		listGroupBuys: connect.NewClient[v1.ListGroupBuysRequest, v1.ListGroupBuysResponse](
			httpClient,
			baseURL+GroupBuyServiceListGroupBuysProcedure,
			connect.WithSchema(groupBuyServiceMethods.ByName("ListGroupBuys")),
			connect.WithClientOptions(opts...),
		),
		listManagerGroupBuys: connect.NewClient[v1.ListManagerGroupBuysRequest, v1.ListManagerGroupBuysResponse](
			httpClient,
			baseURL+GroupBuyServiceListManagerGroupBuysProcedure,
			connect.WithSchema(groupBuyServiceMethods.ByName("ListManagerGroupBuys")),
			connect.WithClientOptions(opts...),
		),
		getGroupBuy: connect.NewClient[v1.GetGroupBuyRequest, v1.GetGroupBuyResponse](
			httpClient,
			baseURL+GroupBuyServiceGetGroupBuyProcedure,
			connect.WithSchema(groupBuyServiceMethods.ByName("GetGroupBuy")),
			connect.WithClientOptions(opts...),
		),
		updateGroupBuy: connect.NewClient[v1.UpdateGroupBuyRequest, v1.UpdateGroupBuyResponse](
			httpClient,
			baseURL+GroupBuyServiceUpdateGroupBuyProcedure,
			connect.WithSchema(groupBuyServiceMethods.ByName("UpdateGroupBuy")),
			connect.WithClientOptions(opts...),
		),
		addProduct: connect.NewClient[v1.AddProductRequest, v1.AddProductResponse](
			httpClient,
			baseURL+GroupBuyServiceAddProductProcedure,
			connect.WithSchema(groupBuyServiceMethods.ByName("AddProduct")),
			connect.WithClientOptions(opts...),
		),
		createCategory: connect.NewClient[v1.CreateCategoryRequest, v1.CreateCategoryResponse](
			httpClient,
			baseURL+GroupBuyServiceCreateCategoryProcedure,
			connect.WithSchema(groupBuyServiceMethods.ByName("CreateCategory")),
			connect.WithClientOptions(opts...),
		),
		listCategories: connect.NewClient[v1.ListCategoriesRequest, v1.ListCategoriesResponse](
			httpClient,
			baseURL+GroupBuyServiceListCategoriesProcedure,
			connect.WithSchema(groupBuyServiceMethods.ByName("ListCategories")),
			connect.WithClientOptions(opts...),
		),
		createOrder: connect.NewClient[v1.CreateOrderRequest, v1.CreateOrderResponse](
			httpClient,
			baseURL+GroupBuyServiceCreateOrderProcedure,
			connect.WithSchema(groupBuyServiceMethods.ByName("CreateOrder")),
			connect.WithClientOptions(opts...),
		),
		cancelOrder: connect.NewClient[v1.CancelOrderRequest, v1.CancelOrderResponse](
			httpClient,
			baseURL+GroupBuyServiceCancelOrderProcedure,
			connect.WithSchema(groupBuyServiceMethods.ByName("CancelOrder")),
			connect.WithClientOptions(opts...),
		),
		getMyGroupBuyOrder: connect.NewClient[v1.GetMyGroupBuyOrderRequest, v1.GetMyGroupBuyOrderResponse](
			httpClient,
			baseURL+GroupBuyServiceGetMyGroupBuyOrderProcedure,
			connect.WithSchema(groupBuyServiceMethods.ByName("GetMyGroupBuyOrder")),
			connect.WithClientOptions(opts...),
		),
		updateOrder: connect.NewClient[v1.UpdateOrderRequest, v1.UpdateOrderResponse](
			httpClient,
			baseURL+GroupBuyServiceUpdateOrderProcedure,
			connect.WithSchema(groupBuyServiceMethods.ByName("UpdateOrder")),
			connect.WithClientOptions(opts...),
		),
		updatePaymentInfo: connect.NewClient[v1.UpdatePaymentInfoRequest, v1.UpdatePaymentInfoResponse](
			httpClient,
			baseURL+GroupBuyServiceUpdatePaymentInfoProcedure,
			connect.WithSchema(groupBuyServiceMethods.ByName("UpdatePaymentInfo")),
			connect.WithClientOptions(opts...),
		),
		getMyOrders: connect.NewClient[v1.GetMyOrdersRequest, v1.GetMyOrdersResponse](
			httpClient,
			baseURL+GroupBuyServiceGetMyOrdersProcedure,
			connect.WithSchema(groupBuyServiceMethods.ByName("GetMyOrders")),
			connect.WithClientOptions(opts...),
		),
		batchUpdateStatus: connect.NewClient[v1.BatchUpdateStatusRequest, v1.BatchUpdateStatusResponse](
			httpClient,
			baseURL+GroupBuyServiceBatchUpdateStatusProcedure,
			connect.WithSchema(groupBuyServiceMethods.ByName("BatchUpdateStatus")),
			connect.WithClientOptions(opts...),
		),
		confirmPayment: connect.NewClient[v1.ConfirmPaymentRequest, v1.ConfirmPaymentResponse](
			httpClient,
			baseURL+GroupBuyServiceConfirmPaymentProcedure,
			connect.WithSchema(groupBuyServiceMethods.ByName("ConfirmPayment")),
			connect.WithClientOptions(opts...),
		),
		listGroupBuyOrders: connect.NewClient[v1.ListGroupBuyOrdersRequest, v1.ListGroupBuyOrdersResponse](
			httpClient,
			baseURL+GroupBuyServiceListGroupBuyOrdersProcedure,
			connect.WithSchema(groupBuyServiceMethods.ByName("ListGroupBuyOrders")),
			connect.WithClientOptions(opts...),
		),
		createPriceTemplate: connect.NewClient[v1.CreatePriceTemplateRequest, v1.CreatePriceTemplateResponse](
			httpClient,
			baseURL+GroupBuyServiceCreatePriceTemplateProcedure,
			connect.WithSchema(groupBuyServiceMethods.ByName("CreatePriceTemplate")),
			connect.WithClientOptions(opts...),
		),
		listPriceTemplates: connect.NewClient[v1.ListPriceTemplatesRequest, v1.ListPriceTemplatesResponse](
			httpClient,
			baseURL+GroupBuyServiceListPriceTemplatesProcedure,
			connect.WithSchema(groupBuyServiceMethods.ByName("ListPriceTemplates")),
			connect.WithClientOptions(opts...),
		),
		getPriceTemplate: connect.NewClient[v1.GetPriceTemplateRequest, v1.GetPriceTemplateResponse](
			httpClient,
			baseURL+GroupBuyServiceGetPriceTemplateProcedure,
			connect.WithSchema(groupBuyServiceMethods.ByName("GetPriceTemplate")),
			connect.WithClientOptions(opts...),
		),
		updatePriceTemplate: connect.NewClient[v1.UpdatePriceTemplateRequest, v1.UpdatePriceTemplateResponse](
			httpClient,
			baseURL+GroupBuyServiceUpdatePriceTemplateProcedure,
			connect.WithSchema(groupBuyServiceMethods.ByName("UpdatePriceTemplate")),
			connect.WithClientOptions(opts...),
		),
		deletePriceTemplate: connect.NewClient[v1.DeletePriceTemplateRequest, v1.DeletePriceTemplateResponse](
			httpClient,
			baseURL+GroupBuyServiceDeletePriceTemplateProcedure,
			connect.WithSchema(groupBuyServiceMethods.ByName("DeletePriceTemplate")),
			connect.WithClientOptions(opts...),
		),
	}
}

// groupBuyServiceClient implements GroupBuyServiceClient.
type groupBuyServiceClient struct {
	createGroupBuy       *connect.Client[v1.CreateGroupBuyRequest, v1.CreateGroupBuyResponse]
	listGroupBuys        *connect.Client[v1.ListGroupBuysRequest, v1.ListGroupBuysResponse]
	listManagerGroupBuys *connect.Client[v1.ListManagerGroupBuysRequest, v1.ListManagerGroupBuysResponse]
	getGroupBuy          *connect.Client[v1.GetGroupBuyRequest, v1.GetGroupBuyResponse]
	updateGroupBuy       *connect.Client[v1.UpdateGroupBuyRequest, v1.UpdateGroupBuyResponse]
	addProduct           *connect.Client[v1.AddProductRequest, v1.AddProductResponse]
	createCategory       *connect.Client[v1.CreateCategoryRequest, v1.CreateCategoryResponse]
	listCategories       *connect.Client[v1.ListCategoriesRequest, v1.ListCategoriesResponse]
	createOrder          *connect.Client[v1.CreateOrderRequest, v1.CreateOrderResponse]
	cancelOrder          *connect.Client[v1.CancelOrderRequest, v1.CancelOrderResponse]
	getMyGroupBuyOrder   *connect.Client[v1.GetMyGroupBuyOrderRequest, v1.GetMyGroupBuyOrderResponse]
	updateOrder          *connect.Client[v1.UpdateOrderRequest, v1.UpdateOrderResponse]
	updatePaymentInfo    *connect.Client[v1.UpdatePaymentInfoRequest, v1.UpdatePaymentInfoResponse]
	getMyOrders          *connect.Client[v1.GetMyOrdersRequest, v1.GetMyOrdersResponse]
	batchUpdateStatus    *connect.Client[v1.BatchUpdateStatusRequest, v1.BatchUpdateStatusResponse]
	confirmPayment       *connect.Client[v1.ConfirmPaymentRequest, v1.ConfirmPaymentResponse]
	listGroupBuyOrders   *connect.Client[v1.ListGroupBuyOrdersRequest, v1.ListGroupBuyOrdersResponse]
	createPriceTemplate  *connect.Client[v1.CreatePriceTemplateRequest, v1.CreatePriceTemplateResponse]
	listPriceTemplates   *connect.Client[v1.ListPriceTemplatesRequest, v1.ListPriceTemplatesResponse]
	getPriceTemplate     *connect.Client[v1.GetPriceTemplateRequest, v1.GetPriceTemplateResponse]
	updatePriceTemplate  *connect.Client[v1.UpdatePriceTemplateRequest, v1.UpdatePriceTemplateResponse]
	deletePriceTemplate  *connect.Client[v1.DeletePriceTemplateRequest, v1.DeletePriceTemplateResponse]
}

// CreateGroupBuy calls buygo.v1.GroupBuyService.CreateGroupBuy.
func (c *groupBuyServiceClient) CreateGroupBuy(ctx context.Context, req *connect.Request[v1.CreateGroupBuyRequest]) (*connect.Response[v1.CreateGroupBuyResponse], error) {
	return c.createGroupBuy.CallUnary(ctx, req)
}

// ListGroupBuys calls buygo.v1.GroupBuyService.ListGroupBuys.
func (c *groupBuyServiceClient) ListGroupBuys(ctx context.Context, req *connect.Request[v1.ListGroupBuysRequest]) (*connect.Response[v1.ListGroupBuysResponse], error) {
	return c.listGroupBuys.CallUnary(ctx, req)
}

// ListManagerGroupBuys calls buygo.v1.GroupBuyService.ListManagerGroupBuys.
func (c *groupBuyServiceClient) ListManagerGroupBuys(ctx context.Context, req *connect.Request[v1.ListManagerGroupBuysRequest]) (*connect.Response[v1.ListManagerGroupBuysResponse], error) {
	return c.listManagerGroupBuys.CallUnary(ctx, req)
}

// GetGroupBuy calls buygo.v1.GroupBuyService.GetGroupBuy.
func (c *groupBuyServiceClient) GetGroupBuy(ctx context.Context, req *connect.Request[v1.GetGroupBuyRequest]) (*connect.Response[v1.GetGroupBuyResponse], error) {
	return c.getGroupBuy.CallUnary(ctx, req)
}

// UpdateGroupBuy calls buygo.v1.GroupBuyService.UpdateGroupBuy.
func (c *groupBuyServiceClient) UpdateGroupBuy(ctx context.Context, req *connect.Request[v1.UpdateGroupBuyRequest]) (*connect.Response[v1.UpdateGroupBuyResponse], error) {
	return c.updateGroupBuy.CallUnary(ctx, req)
}

// AddProduct calls buygo.v1.GroupBuyService.AddProduct.
func (c *groupBuyServiceClient) AddProduct(ctx context.Context, req *connect.Request[v1.AddProductRequest]) (*connect.Response[v1.AddProductResponse], error) {
	return c.addProduct.CallUnary(ctx, req)
}

// CreateCategory calls buygo.v1.GroupBuyService.CreateCategory.
func (c *groupBuyServiceClient) CreateCategory(ctx context.Context, req *connect.Request[v1.CreateCategoryRequest]) (*connect.Response[v1.CreateCategoryResponse], error) {
	return c.createCategory.CallUnary(ctx, req)
}

// ListCategories calls buygo.v1.GroupBuyService.ListCategories.
func (c *groupBuyServiceClient) ListCategories(ctx context.Context, req *connect.Request[v1.ListCategoriesRequest]) (*connect.Response[v1.ListCategoriesResponse], error) {
	return c.listCategories.CallUnary(ctx, req)
}

// CreateOrder calls buygo.v1.GroupBuyService.CreateOrder.
func (c *groupBuyServiceClient) CreateOrder(ctx context.Context, req *connect.Request[v1.CreateOrderRequest]) (*connect.Response[v1.CreateOrderResponse], error) {
	return c.createOrder.CallUnary(ctx, req)
}

// CancelOrder calls buygo.v1.GroupBuyService.CancelOrder.
func (c *groupBuyServiceClient) CancelOrder(ctx context.Context, req *connect.Request[v1.CancelOrderRequest]) (*connect.Response[v1.CancelOrderResponse], error) {
	return c.cancelOrder.CallUnary(ctx, req)
}

// GetMyGroupBuyOrder calls buygo.v1.GroupBuyService.GetMyGroupBuyOrder.
func (c *groupBuyServiceClient) GetMyGroupBuyOrder(ctx context.Context, req *connect.Request[v1.GetMyGroupBuyOrderRequest]) (*connect.Response[v1.GetMyGroupBuyOrderResponse], error) {
	return c.getMyGroupBuyOrder.CallUnary(ctx, req)
}

// UpdateOrder calls buygo.v1.GroupBuyService.UpdateOrder.
func (c *groupBuyServiceClient) UpdateOrder(ctx context.Context, req *connect.Request[v1.UpdateOrderRequest]) (*connect.Response[v1.UpdateOrderResponse], error) {
	return c.updateOrder.CallUnary(ctx, req)
}

// UpdatePaymentInfo calls buygo.v1.GroupBuyService.UpdatePaymentInfo.
func (c *groupBuyServiceClient) UpdatePaymentInfo(ctx context.Context, req *connect.Request[v1.UpdatePaymentInfoRequest]) (*connect.Response[v1.UpdatePaymentInfoResponse], error) {
	return c.updatePaymentInfo.CallUnary(ctx, req)
}

// GetMyOrders calls buygo.v1.GroupBuyService.GetMyOrders.
func (c *groupBuyServiceClient) GetMyOrders(ctx context.Context, req *connect.Request[v1.GetMyOrdersRequest]) (*connect.Response[v1.GetMyOrdersResponse], error) {
	return c.getMyOrders.CallUnary(ctx, req)
}

// BatchUpdateStatus calls buygo.v1.GroupBuyService.BatchUpdateStatus.
func (c *groupBuyServiceClient) BatchUpdateStatus(ctx context.Context, req *connect.Request[v1.BatchUpdateStatusRequest]) (*connect.Response[v1.BatchUpdateStatusResponse], error) {
	return c.batchUpdateStatus.CallUnary(ctx, req)
}

// ConfirmPayment calls buygo.v1.GroupBuyService.ConfirmPayment.
func (c *groupBuyServiceClient) ConfirmPayment(ctx context.Context, req *connect.Request[v1.ConfirmPaymentRequest]) (*connect.Response[v1.ConfirmPaymentResponse], error) {
	return c.confirmPayment.CallUnary(ctx, req)
}

// ListGroupBuyOrders calls buygo.v1.GroupBuyService.ListGroupBuyOrders.
func (c *groupBuyServiceClient) ListGroupBuyOrders(ctx context.Context, req *connect.Request[v1.ListGroupBuyOrdersRequest]) (*connect.Response[v1.ListGroupBuyOrdersResponse], error) {
	return c.listGroupBuyOrders.CallUnary(ctx, req)
}

// CreatePriceTemplate calls buygo.v1.GroupBuyService.CreatePriceTemplate.
func (c *groupBuyServiceClient) CreatePriceTemplate(ctx context.Context, req *connect.Request[v1.CreatePriceTemplateRequest]) (*connect.Response[v1.CreatePriceTemplateResponse], error) {
	return c.createPriceTemplate.CallUnary(ctx, req)
}

// ListPriceTemplates calls buygo.v1.GroupBuyService.ListPriceTemplates.
func (c *groupBuyServiceClient) ListPriceTemplates(ctx context.Context, req *connect.Request[v1.ListPriceTemplatesRequest]) (*connect.Response[v1.ListPriceTemplatesResponse], error) {
	return c.listPriceTemplates.CallUnary(ctx, req)
}

// GetPriceTemplate calls buygo.v1.GroupBuyService.GetPriceTemplate.
func (c *groupBuyServiceClient) GetPriceTemplate(ctx context.Context, req *connect.Request[v1.GetPriceTemplateRequest]) (*connect.Response[v1.GetPriceTemplateResponse], error) {
	return c.getPriceTemplate.CallUnary(ctx, req)
}

// UpdatePriceTemplate calls buygo.v1.GroupBuyService.UpdatePriceTemplate.
func (c *groupBuyServiceClient) UpdatePriceTemplate(ctx context.Context, req *connect.Request[v1.UpdatePriceTemplateRequest]) (*connect.Response[v1.UpdatePriceTemplateResponse], error) {
	return c.updatePriceTemplate.CallUnary(ctx, req)
}

// DeletePriceTemplate calls buygo.v1.GroupBuyService.DeletePriceTemplate.
func (c *groupBuyServiceClient) DeletePriceTemplate(ctx context.Context, req *connect.Request[v1.DeletePriceTemplateRequest]) (*connect.Response[v1.DeletePriceTemplateResponse], error) {
	return c.deletePriceTemplate.CallUnary(ctx, req)
}

// GroupBuyServiceHandler is an implementation of the buygo.v1.GroupBuyService service.
type GroupBuyServiceHandler interface {
	// GroupBuy Management (Creator/Admin)
	CreateGroupBuy(context.Context, *connect.Request[v1.CreateGroupBuyRequest]) (*connect.Response[v1.CreateGroupBuyResponse], error)
	ListGroupBuys(context.Context, *connect.Request[v1.ListGroupBuysRequest]) (*connect.Response[v1.ListGroupBuysResponse], error)
	ListManagerGroupBuys(context.Context, *connect.Request[v1.ListManagerGroupBuysRequest]) (*connect.Response[v1.ListManagerGroupBuysResponse], error)
	GetGroupBuy(context.Context, *connect.Request[v1.GetGroupBuyRequest]) (*connect.Response[v1.GetGroupBuyResponse], error)
	UpdateGroupBuy(context.Context, *connect.Request[v1.UpdateGroupBuyRequest]) (*connect.Response[v1.UpdateGroupBuyResponse], error)
	// Product Management (Creator/Admin)
	AddProduct(context.Context, *connect.Request[v1.AddProductRequest]) (*connect.Response[v1.AddProductResponse], error)
	// Category (Template) Methods
	CreateCategory(context.Context, *connect.Request[v1.CreateCategoryRequest]) (*connect.Response[v1.CreateCategoryResponse], error)
	ListCategories(context.Context, *connect.Request[v1.ListCategoriesRequest]) (*connect.Response[v1.ListCategoriesResponse], error)
	// Order Management (User)
	CreateOrder(context.Context, *connect.Request[v1.CreateOrderRequest]) (*connect.Response[v1.CreateOrderResponse], error)
	CancelOrder(context.Context, *connect.Request[v1.CancelOrderRequest]) (*connect.Response[v1.CancelOrderResponse], error)
	GetMyGroupBuyOrder(context.Context, *connect.Request[v1.GetMyGroupBuyOrderRequest]) (*connect.Response[v1.GetMyGroupBuyOrderResponse], error)
	UpdateOrder(context.Context, *connect.Request[v1.UpdateOrderRequest]) (*connect.Response[v1.UpdateOrderResponse], error)
	UpdatePaymentInfo(context.Context, *connect.Request[v1.UpdatePaymentInfoRequest]) (*connect.Response[v1.UpdatePaymentInfoResponse], error)
	GetMyOrders(context.Context, *connect.Request[v1.GetMyOrdersRequest]) (*connect.Response[v1.GetMyOrdersResponse], error)
	// Order Management (Manager)
	// Batch update status of items (FIFO)
	BatchUpdateStatus(context.Context, *connect.Request[v1.BatchUpdateStatusRequest]) (*connect.Response[v1.BatchUpdateStatusResponse], error)
	// Confirm user payment
	// Confirm user payment
	ConfirmPayment(context.Context, *connect.Request[v1.ConfirmPaymentRequest]) (*connect.Response[v1.ConfirmPaymentResponse], error)
	// Manager: List Orders for a GroupBuy
	ListGroupBuyOrders(context.Context, *connect.Request[v1.ListGroupBuyOrdersRequest]) (*connect.Response[v1.ListGroupBuyOrdersResponse], error)
	// Price Templates (Admin Only)
	CreatePriceTemplate(context.Context, *connect.Request[v1.CreatePriceTemplateRequest]) (*connect.Response[v1.CreatePriceTemplateResponse], error)
	ListPriceTemplates(context.Context, *connect.Request[v1.ListPriceTemplatesRequest]) (*connect.Response[v1.ListPriceTemplatesResponse], error)
	GetPriceTemplate(context.Context, *connect.Request[v1.GetPriceTemplateRequest]) (*connect.Response[v1.GetPriceTemplateResponse], error)
	UpdatePriceTemplate(context.Context, *connect.Request[v1.UpdatePriceTemplateRequest]) (*connect.Response[v1.UpdatePriceTemplateResponse], error)
	DeletePriceTemplate(context.Context, *connect.Request[v1.DeletePriceTemplateRequest]) (*connect.Response[v1.DeletePriceTemplateResponse], error)
}

// NewGroupBuyServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGroupBuyServiceHandler(svc GroupBuyServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	groupBuyServiceMethods := v1.File_api_v1_groupbuy_proto.Services().ByName("GroupBuyService").Methods()
	groupBuyServiceCreateGroupBuyHandler := connect.NewUnaryHandler(
		GroupBuyServiceCreateGroupBuyProcedure,
		svc.CreateGroupBuy,
		connect.WithSchema(groupBuyServiceMethods.ByName("CreateGroupBuy")),
		connect.WithHandlerOptions(opts...),
	)
	groupBuyServiceListGroupBuysHandler := connect.NewUnaryHandler(
		GroupBuyServiceListGroupBuysProcedure,
		svc.ListGroupBuys,
		connect.WithSchema(groupBuyServiceMethods.ByName("ListGroupBuys")),
		connect.WithHandlerOptions(opts...),
	)
	groupBuyServiceListManagerGroupBuysHandler := connect.NewUnaryHandler(
		GroupBuyServiceListManagerGroupBuysProcedure,
		svc.ListManagerGroupBuys,
		connect.WithSchema(groupBuyServiceMethods.ByName("ListManagerGroupBuys")),
		connect.WithHandlerOptions(opts...),
	)
	groupBuyServiceGetGroupBuyHandler := connect.NewUnaryHandler(
		GroupBuyServiceGetGroupBuyProcedure,
		svc.GetGroupBuy,
		connect.WithSchema(groupBuyServiceMethods.ByName("GetGroupBuy")),
		connect.WithHandlerOptions(opts...),
	)
	groupBuyServiceUpdateGroupBuyHandler := connect.NewUnaryHandler(
		GroupBuyServiceUpdateGroupBuyProcedure,
		svc.UpdateGroupBuy,
		connect.WithSchema(groupBuyServiceMethods.ByName("UpdateGroupBuy")),
		connect.WithHandlerOptions(opts...),
	)
	groupBuyServiceAddProductHandler := connect.NewUnaryHandler(
		GroupBuyServiceAddProductProcedure,
		svc.AddProduct,
		connect.WithSchema(groupBuyServiceMethods.ByName("AddProduct")),
		connect.WithHandlerOptions(opts...),
	)
	groupBuyServiceCreateCategoryHandler := connect.NewUnaryHandler(
		GroupBuyServiceCreateCategoryProcedure,
		svc.CreateCategory,
		connect.WithSchema(groupBuyServiceMethods.ByName("CreateCategory")),
		connect.WithHandlerOptions(opts...),
	)
	groupBuyServiceListCategoriesHandler := connect.NewUnaryHandler(
		GroupBuyServiceListCategoriesProcedure,
		svc.ListCategories,
		connect.WithSchema(groupBuyServiceMethods.ByName("ListCategories")),
		connect.WithHandlerOptions(opts...),
	)
	groupBuyServiceCreateOrderHandler := connect.NewUnaryHandler(
		GroupBuyServiceCreateOrderProcedure,
		svc.CreateOrder,
		connect.WithSchema(groupBuyServiceMethods.ByName("CreateOrder")),
		connect.WithHandlerOptions(opts...),
	)
	groupBuyServiceCancelOrderHandler := connect.NewUnaryHandler(
		GroupBuyServiceCancelOrderProcedure,
		svc.CancelOrder,
		connect.WithSchema(groupBuyServiceMethods.ByName("CancelOrder")),
		connect.WithHandlerOptions(opts...),
	)
	groupBuyServiceGetMyGroupBuyOrderHandler := connect.NewUnaryHandler(
		GroupBuyServiceGetMyGroupBuyOrderProcedure,
		svc.GetMyGroupBuyOrder,
		connect.WithSchema(groupBuyServiceMethods.ByName("GetMyGroupBuyOrder")),
		connect.WithHandlerOptions(opts...),
	)
	groupBuyServiceUpdateOrderHandler := connect.NewUnaryHandler(
		GroupBuyServiceUpdateOrderProcedure,
		svc.UpdateOrder,
		connect.WithSchema(groupBuyServiceMethods.ByName("UpdateOrder")),
		connect.WithHandlerOptions(opts...),
	)
	groupBuyServiceUpdatePaymentInfoHandler := connect.NewUnaryHandler(
		GroupBuyServiceUpdatePaymentInfoProcedure,
		svc.UpdatePaymentInfo,
		connect.WithSchema(groupBuyServiceMethods.ByName("UpdatePaymentInfo")),
		connect.WithHandlerOptions(opts...),
	)
	groupBuyServiceGetMyOrdersHandler := connect.NewUnaryHandler(
		GroupBuyServiceGetMyOrdersProcedure,
		svc.GetMyOrders,
		connect.WithSchema(groupBuyServiceMethods.ByName("GetMyOrders")),
		connect.WithHandlerOptions(opts...),
	)
	groupBuyServiceBatchUpdateStatusHandler := connect.NewUnaryHandler(
		GroupBuyServiceBatchUpdateStatusProcedure,
		svc.BatchUpdateStatus,
		connect.WithSchema(groupBuyServiceMethods.ByName("BatchUpdateStatus")),
		connect.WithHandlerOptions(opts...),
	)
	groupBuyServiceConfirmPaymentHandler := connect.NewUnaryHandler(
		GroupBuyServiceConfirmPaymentProcedure,
		svc.ConfirmPayment,
		connect.WithSchema(groupBuyServiceMethods.ByName("ConfirmPayment")),
		connect.WithHandlerOptions(opts...),
	)
	groupBuyServiceListGroupBuyOrdersHandler := connect.NewUnaryHandler(
		GroupBuyServiceListGroupBuyOrdersProcedure,
		svc.ListGroupBuyOrders,
		connect.WithSchema(groupBuyServiceMethods.ByName("ListGroupBuyOrders")),
		connect.WithHandlerOptions(opts...),
	)
	groupBuyServiceCreatePriceTemplateHandler := connect.NewUnaryHandler(
		GroupBuyServiceCreatePriceTemplateProcedure,
		svc.CreatePriceTemplate,
		connect.WithSchema(groupBuyServiceMethods.ByName("CreatePriceTemplate")),
		connect.WithHandlerOptions(opts...),
	)
	groupBuyServiceListPriceTemplatesHandler := connect.NewUnaryHandler(
		GroupBuyServiceListPriceTemplatesProcedure,
		svc.ListPriceTemplates,
		connect.WithSchema(groupBuyServiceMethods.ByName("ListPriceTemplates")),
		connect.WithHandlerOptions(opts...),
	)
	groupBuyServiceGetPriceTemplateHandler := connect.NewUnaryHandler(
		GroupBuyServiceGetPriceTemplateProcedure,
		svc.GetPriceTemplate,
		connect.WithSchema(groupBuyServiceMethods.ByName("GetPriceTemplate")),
		connect.WithHandlerOptions(opts...),
	)
	groupBuyServiceUpdatePriceTemplateHandler := connect.NewUnaryHandler(
		GroupBuyServiceUpdatePriceTemplateProcedure,
		svc.UpdatePriceTemplate,
		connect.WithSchema(groupBuyServiceMethods.ByName("UpdatePriceTemplate")),
		connect.WithHandlerOptions(opts...),
	)
	groupBuyServiceDeletePriceTemplateHandler := connect.NewUnaryHandler(
		GroupBuyServiceDeletePriceTemplateProcedure,
		svc.DeletePriceTemplate,
		connect.WithSchema(groupBuyServiceMethods.ByName("DeletePriceTemplate")),
		connect.WithHandlerOptions(opts...),
	)
	return "/buygo.v1.GroupBuyService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GroupBuyServiceCreateGroupBuyProcedure:
			groupBuyServiceCreateGroupBuyHandler.ServeHTTP(w, r)
		case GroupBuyServiceListGroupBuysProcedure:
			groupBuyServiceListGroupBuysHandler.ServeHTTP(w, r)
		case GroupBuyServiceListManagerGroupBuysProcedure:
			groupBuyServiceListManagerGroupBuysHandler.ServeHTTP(w, r)
		case GroupBuyServiceGetGroupBuyProcedure:
			groupBuyServiceGetGroupBuyHandler.ServeHTTP(w, r)
		case GroupBuyServiceUpdateGroupBuyProcedure:
			groupBuyServiceUpdateGroupBuyHandler.ServeHTTP(w, r)
		case GroupBuyServiceAddProductProcedure:
			groupBuyServiceAddProductHandler.ServeHTTP(w, r)
		case GroupBuyServiceCreateCategoryProcedure:
			groupBuyServiceCreateCategoryHandler.ServeHTTP(w, r)
		case GroupBuyServiceListCategoriesProcedure:
			groupBuyServiceListCategoriesHandler.ServeHTTP(w, r)
		case GroupBuyServiceCreateOrderProcedure:
			groupBuyServiceCreateOrderHandler.ServeHTTP(w, r)
		case GroupBuyServiceCancelOrderProcedure:
			groupBuyServiceCancelOrderHandler.ServeHTTP(w, r)
		case GroupBuyServiceGetMyGroupBuyOrderProcedure:
			groupBuyServiceGetMyGroupBuyOrderHandler.ServeHTTP(w, r)
		case GroupBuyServiceUpdateOrderProcedure:
			groupBuyServiceUpdateOrderHandler.ServeHTTP(w, r)
		case GroupBuyServiceUpdatePaymentInfoProcedure:
			groupBuyServiceUpdatePaymentInfoHandler.ServeHTTP(w, r)
		case GroupBuyServiceGetMyOrdersProcedure:
			groupBuyServiceGetMyOrdersHandler.ServeHTTP(w, r)
		case GroupBuyServiceBatchUpdateStatusProcedure:
			groupBuyServiceBatchUpdateStatusHandler.ServeHTTP(w, r)
		case GroupBuyServiceConfirmPaymentProcedure:
			groupBuyServiceConfirmPaymentHandler.ServeHTTP(w, r)
		case GroupBuyServiceListGroupBuyOrdersProcedure:
			groupBuyServiceListGroupBuyOrdersHandler.ServeHTTP(w, r)
		case GroupBuyServiceCreatePriceTemplateProcedure:
			groupBuyServiceCreatePriceTemplateHandler.ServeHTTP(w, r)
		case GroupBuyServiceListPriceTemplatesProcedure:
			groupBuyServiceListPriceTemplatesHandler.ServeHTTP(w, r)
		case GroupBuyServiceGetPriceTemplateProcedure:
			groupBuyServiceGetPriceTemplateHandler.ServeHTTP(w, r)
		case GroupBuyServiceUpdatePriceTemplateProcedure:
			groupBuyServiceUpdatePriceTemplateHandler.ServeHTTP(w, r)
		case GroupBuyServiceDeletePriceTemplateProcedure:
			groupBuyServiceDeletePriceTemplateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGroupBuyServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGroupBuyServiceHandler struct{}

func (UnimplementedGroupBuyServiceHandler) CreateGroupBuy(context.Context, *connect.Request[v1.CreateGroupBuyRequest]) (*connect.Response[v1.CreateGroupBuyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.GroupBuyService.CreateGroupBuy is not implemented"))
}

func (UnimplementedGroupBuyServiceHandler) ListGroupBuys(context.Context, *connect.Request[v1.ListGroupBuysRequest]) (*connect.Response[v1.ListGroupBuysResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.GroupBuyService.ListGroupBuys is not implemented"))
}

func (UnimplementedGroupBuyServiceHandler) ListManagerGroupBuys(context.Context, *connect.Request[v1.ListManagerGroupBuysRequest]) (*connect.Response[v1.ListManagerGroupBuysResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.GroupBuyService.ListManagerGroupBuys is not implemented"))
}

func (UnimplementedGroupBuyServiceHandler) GetGroupBuy(context.Context, *connect.Request[v1.GetGroupBuyRequest]) (*connect.Response[v1.GetGroupBuyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.GroupBuyService.GetGroupBuy is not implemented"))
}

func (UnimplementedGroupBuyServiceHandler) UpdateGroupBuy(context.Context, *connect.Request[v1.UpdateGroupBuyRequest]) (*connect.Response[v1.UpdateGroupBuyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.GroupBuyService.UpdateGroupBuy is not implemented"))
}

func (UnimplementedGroupBuyServiceHandler) AddProduct(context.Context, *connect.Request[v1.AddProductRequest]) (*connect.Response[v1.AddProductResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.GroupBuyService.AddProduct is not implemented"))
}

func (UnimplementedGroupBuyServiceHandler) CreateCategory(context.Context, *connect.Request[v1.CreateCategoryRequest]) (*connect.Response[v1.CreateCategoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.GroupBuyService.CreateCategory is not implemented"))
}

func (UnimplementedGroupBuyServiceHandler) ListCategories(context.Context, *connect.Request[v1.ListCategoriesRequest]) (*connect.Response[v1.ListCategoriesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.GroupBuyService.ListCategories is not implemented"))
}

func (UnimplementedGroupBuyServiceHandler) CreateOrder(context.Context, *connect.Request[v1.CreateOrderRequest]) (*connect.Response[v1.CreateOrderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.GroupBuyService.CreateOrder is not implemented"))
}

func (UnimplementedGroupBuyServiceHandler) CancelOrder(context.Context, *connect.Request[v1.CancelOrderRequest]) (*connect.Response[v1.CancelOrderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.GroupBuyService.CancelOrder is not implemented"))
}

func (UnimplementedGroupBuyServiceHandler) GetMyGroupBuyOrder(context.Context, *connect.Request[v1.GetMyGroupBuyOrderRequest]) (*connect.Response[v1.GetMyGroupBuyOrderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.GroupBuyService.GetMyGroupBuyOrder is not implemented"))
}

func (UnimplementedGroupBuyServiceHandler) UpdateOrder(context.Context, *connect.Request[v1.UpdateOrderRequest]) (*connect.Response[v1.UpdateOrderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.GroupBuyService.UpdateOrder is not implemented"))
}

func (UnimplementedGroupBuyServiceHandler) UpdatePaymentInfo(context.Context, *connect.Request[v1.UpdatePaymentInfoRequest]) (*connect.Response[v1.UpdatePaymentInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.GroupBuyService.UpdatePaymentInfo is not implemented"))
}

func (UnimplementedGroupBuyServiceHandler) GetMyOrders(context.Context, *connect.Request[v1.GetMyOrdersRequest]) (*connect.Response[v1.GetMyOrdersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.GroupBuyService.GetMyOrders is not implemented"))
}

func (UnimplementedGroupBuyServiceHandler) BatchUpdateStatus(context.Context, *connect.Request[v1.BatchUpdateStatusRequest]) (*connect.Response[v1.BatchUpdateStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.GroupBuyService.BatchUpdateStatus is not implemented"))
}

func (UnimplementedGroupBuyServiceHandler) ConfirmPayment(context.Context, *connect.Request[v1.ConfirmPaymentRequest]) (*connect.Response[v1.ConfirmPaymentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.GroupBuyService.ConfirmPayment is not implemented"))
}

func (UnimplementedGroupBuyServiceHandler) ListGroupBuyOrders(context.Context, *connect.Request[v1.ListGroupBuyOrdersRequest]) (*connect.Response[v1.ListGroupBuyOrdersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.GroupBuyService.ListGroupBuyOrders is not implemented"))
}

func (UnimplementedGroupBuyServiceHandler) CreatePriceTemplate(context.Context, *connect.Request[v1.CreatePriceTemplateRequest]) (*connect.Response[v1.CreatePriceTemplateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.GroupBuyService.CreatePriceTemplate is not implemented"))
}

func (UnimplementedGroupBuyServiceHandler) ListPriceTemplates(context.Context, *connect.Request[v1.ListPriceTemplatesRequest]) (*connect.Response[v1.ListPriceTemplatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.GroupBuyService.ListPriceTemplates is not implemented"))
}

func (UnimplementedGroupBuyServiceHandler) GetPriceTemplate(context.Context, *connect.Request[v1.GetPriceTemplateRequest]) (*connect.Response[v1.GetPriceTemplateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.GroupBuyService.GetPriceTemplate is not implemented"))
}

func (UnimplementedGroupBuyServiceHandler) UpdatePriceTemplate(context.Context, *connect.Request[v1.UpdatePriceTemplateRequest]) (*connect.Response[v1.UpdatePriceTemplateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.GroupBuyService.UpdatePriceTemplate is not implemented"))
}

func (UnimplementedGroupBuyServiceHandler) DeletePriceTemplate(context.Context, *connect.Request[v1.DeletePriceTemplateRequest]) (*connect.Response[v1.DeletePriceTemplateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.GroupBuyService.DeletePriceTemplate is not implemented"))
}
