// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/v1/project.proto

package buygov1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/buygo/buygo-api/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProjectServiceName is the fully-qualified name of the ProjectService service.
	ProjectServiceName = "buygo.v1.ProjectService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProjectServiceCreateProjectProcedure is the fully-qualified name of the ProjectService's
	// CreateProject RPC.
	ProjectServiceCreateProjectProcedure = "/buygo.v1.ProjectService/CreateProject"
	// ProjectServiceListProjectsProcedure is the fully-qualified name of the ProjectService's
	// ListProjects RPC.
	ProjectServiceListProjectsProcedure = "/buygo.v1.ProjectService/ListProjects"
	// ProjectServiceListManagerProjectsProcedure is the fully-qualified name of the ProjectService's
	// ListManagerProjects RPC.
	ProjectServiceListManagerProjectsProcedure = "/buygo.v1.ProjectService/ListManagerProjects"
	// ProjectServiceGetProjectProcedure is the fully-qualified name of the ProjectService's GetProject
	// RPC.
	ProjectServiceGetProjectProcedure = "/buygo.v1.ProjectService/GetProject"
	// ProjectServiceUpdateProjectProcedure is the fully-qualified name of the ProjectService's
	// UpdateProject RPC.
	ProjectServiceUpdateProjectProcedure = "/buygo.v1.ProjectService/UpdateProject"
	// ProjectServiceAddProductProcedure is the fully-qualified name of the ProjectService's AddProduct
	// RPC.
	ProjectServiceAddProductProcedure = "/buygo.v1.ProjectService/AddProduct"
	// ProjectServiceCreateCategoryProcedure is the fully-qualified name of the ProjectService's
	// CreateCategory RPC.
	ProjectServiceCreateCategoryProcedure = "/buygo.v1.ProjectService/CreateCategory"
	// ProjectServiceListCategoriesProcedure is the fully-qualified name of the ProjectService's
	// ListCategories RPC.
	ProjectServiceListCategoriesProcedure = "/buygo.v1.ProjectService/ListCategories"
	// ProjectServiceCreateOrderProcedure is the fully-qualified name of the ProjectService's
	// CreateOrder RPC.
	ProjectServiceCreateOrderProcedure = "/buygo.v1.ProjectService/CreateOrder"
	// ProjectServiceCancelOrderProcedure is the fully-qualified name of the ProjectService's
	// CancelOrder RPC.
	ProjectServiceCancelOrderProcedure = "/buygo.v1.ProjectService/CancelOrder"
	// ProjectServiceGetMyProjectOrderProcedure is the fully-qualified name of the ProjectService's
	// GetMyProjectOrder RPC.
	ProjectServiceGetMyProjectOrderProcedure = "/buygo.v1.ProjectService/GetMyProjectOrder"
	// ProjectServiceUpdateOrderProcedure is the fully-qualified name of the ProjectService's
	// UpdateOrder RPC.
	ProjectServiceUpdateOrderProcedure = "/buygo.v1.ProjectService/UpdateOrder"
	// ProjectServiceUpdatePaymentInfoProcedure is the fully-qualified name of the ProjectService's
	// UpdatePaymentInfo RPC.
	ProjectServiceUpdatePaymentInfoProcedure = "/buygo.v1.ProjectService/UpdatePaymentInfo"
	// ProjectServiceGetMyOrdersProcedure is the fully-qualified name of the ProjectService's
	// GetMyOrders RPC.
	ProjectServiceGetMyOrdersProcedure = "/buygo.v1.ProjectService/GetMyOrders"
	// ProjectServiceBatchUpdateStatusProcedure is the fully-qualified name of the ProjectService's
	// BatchUpdateStatus RPC.
	ProjectServiceBatchUpdateStatusProcedure = "/buygo.v1.ProjectService/BatchUpdateStatus"
	// ProjectServiceConfirmPaymentProcedure is the fully-qualified name of the ProjectService's
	// ConfirmPayment RPC.
	ProjectServiceConfirmPaymentProcedure = "/buygo.v1.ProjectService/ConfirmPayment"
	// ProjectServiceListProjectOrdersProcedure is the fully-qualified name of the ProjectService's
	// ListProjectOrders RPC.
	ProjectServiceListProjectOrdersProcedure = "/buygo.v1.ProjectService/ListProjectOrders"
	// ProjectServiceCreatePriceTemplateProcedure is the fully-qualified name of the ProjectService's
	// CreatePriceTemplate RPC.
	ProjectServiceCreatePriceTemplateProcedure = "/buygo.v1.ProjectService/CreatePriceTemplate"
	// ProjectServiceListPriceTemplatesProcedure is the fully-qualified name of the ProjectService's
	// ListPriceTemplates RPC.
	ProjectServiceListPriceTemplatesProcedure = "/buygo.v1.ProjectService/ListPriceTemplates"
	// ProjectServiceGetPriceTemplateProcedure is the fully-qualified name of the ProjectService's
	// GetPriceTemplate RPC.
	ProjectServiceGetPriceTemplateProcedure = "/buygo.v1.ProjectService/GetPriceTemplate"
	// ProjectServiceUpdatePriceTemplateProcedure is the fully-qualified name of the ProjectService's
	// UpdatePriceTemplate RPC.
	ProjectServiceUpdatePriceTemplateProcedure = "/buygo.v1.ProjectService/UpdatePriceTemplate"
	// ProjectServiceDeletePriceTemplateProcedure is the fully-qualified name of the ProjectService's
	// DeletePriceTemplate RPC.
	ProjectServiceDeletePriceTemplateProcedure = "/buygo.v1.ProjectService/DeletePriceTemplate"
)

// ProjectServiceClient is a client for the buygo.v1.ProjectService service.
type ProjectServiceClient interface {
	// Project Management (Creator/Admin)
	CreateProject(context.Context, *connect.Request[v1.CreateProjectRequest]) (*connect.Response[v1.CreateProjectResponse], error)
	ListProjects(context.Context, *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error)
	ListManagerProjects(context.Context, *connect.Request[v1.ListManagerProjectsRequest]) (*connect.Response[v1.ListManagerProjectsResponse], error)
	GetProject(context.Context, *connect.Request[v1.GetProjectRequest]) (*connect.Response[v1.GetProjectResponse], error)
	UpdateProject(context.Context, *connect.Request[v1.UpdateProjectRequest]) (*connect.Response[v1.UpdateProjectResponse], error)
	// Product Management (Creator/Admin)
	AddProduct(context.Context, *connect.Request[v1.AddProductRequest]) (*connect.Response[v1.AddProductResponse], error)
	// Category (Template) Methods
	CreateCategory(context.Context, *connect.Request[v1.CreateCategoryRequest]) (*connect.Response[v1.CreateCategoryResponse], error)
	ListCategories(context.Context, *connect.Request[v1.ListCategoriesRequest]) (*connect.Response[v1.ListCategoriesResponse], error)
	// Order Management (User)
	CreateOrder(context.Context, *connect.Request[v1.CreateOrderRequest]) (*connect.Response[v1.CreateOrderResponse], error)
	CancelOrder(context.Context, *connect.Request[v1.CancelOrderRequest]) (*connect.Response[v1.CancelOrderResponse], error)
	GetMyProjectOrder(context.Context, *connect.Request[v1.GetMyProjectOrderRequest]) (*connect.Response[v1.GetMyProjectOrderResponse], error)
	UpdateOrder(context.Context, *connect.Request[v1.UpdateOrderRequest]) (*connect.Response[v1.UpdateOrderResponse], error)
	UpdatePaymentInfo(context.Context, *connect.Request[v1.UpdatePaymentInfoRequest]) (*connect.Response[v1.UpdatePaymentInfoResponse], error)
	GetMyOrders(context.Context, *connect.Request[v1.GetMyOrdersRequest]) (*connect.Response[v1.GetMyOrdersResponse], error)
	// Order Management (Manager)
	// Batch update status of items (FIFO)
	BatchUpdateStatus(context.Context, *connect.Request[v1.BatchUpdateStatusRequest]) (*connect.Response[v1.BatchUpdateStatusResponse], error)
	// Confirm user payment
	// Confirm user payment
	ConfirmPayment(context.Context, *connect.Request[v1.ConfirmPaymentRequest]) (*connect.Response[v1.ConfirmPaymentResponse], error)
	// Manager: List Orders for a Project
	ListProjectOrders(context.Context, *connect.Request[v1.ListProjectOrdersRequest]) (*connect.Response[v1.ListProjectOrdersResponse], error)
	// Price Templates (Admin Only)
	CreatePriceTemplate(context.Context, *connect.Request[v1.CreatePriceTemplateRequest]) (*connect.Response[v1.CreatePriceTemplateResponse], error)
	ListPriceTemplates(context.Context, *connect.Request[v1.ListPriceTemplatesRequest]) (*connect.Response[v1.ListPriceTemplatesResponse], error)
	GetPriceTemplate(context.Context, *connect.Request[v1.GetPriceTemplateRequest]) (*connect.Response[v1.GetPriceTemplateResponse], error)
	UpdatePriceTemplate(context.Context, *connect.Request[v1.UpdatePriceTemplateRequest]) (*connect.Response[v1.UpdatePriceTemplateResponse], error)
	DeletePriceTemplate(context.Context, *connect.Request[v1.DeletePriceTemplateRequest]) (*connect.Response[v1.DeletePriceTemplateResponse], error)
}

// NewProjectServiceClient constructs a client for the buygo.v1.ProjectService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProjectServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProjectServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	projectServiceMethods := v1.File_api_v1_project_proto.Services().ByName("ProjectService").Methods()
	return &projectServiceClient{
		createProject: connect.NewClient[v1.CreateProjectRequest, v1.CreateProjectResponse](
			httpClient,
			baseURL+ProjectServiceCreateProjectProcedure,
			connect.WithSchema(projectServiceMethods.ByName("CreateProject")),
			connect.WithClientOptions(opts...),
		),
		listProjects: connect.NewClient[v1.ListProjectsRequest, v1.ListProjectsResponse](
			httpClient,
			baseURL+ProjectServiceListProjectsProcedure,
			connect.WithSchema(projectServiceMethods.ByName("ListProjects")),
			connect.WithClientOptions(opts...),
		),
		listManagerProjects: connect.NewClient[v1.ListManagerProjectsRequest, v1.ListManagerProjectsResponse](
			httpClient,
			baseURL+ProjectServiceListManagerProjectsProcedure,
			connect.WithSchema(projectServiceMethods.ByName("ListManagerProjects")),
			connect.WithClientOptions(opts...),
		),
		getProject: connect.NewClient[v1.GetProjectRequest, v1.GetProjectResponse](
			httpClient,
			baseURL+ProjectServiceGetProjectProcedure,
			connect.WithSchema(projectServiceMethods.ByName("GetProject")),
			connect.WithClientOptions(opts...),
		),
		updateProject: connect.NewClient[v1.UpdateProjectRequest, v1.UpdateProjectResponse](
			httpClient,
			baseURL+ProjectServiceUpdateProjectProcedure,
			connect.WithSchema(projectServiceMethods.ByName("UpdateProject")),
			connect.WithClientOptions(opts...),
		),
		addProduct: connect.NewClient[v1.AddProductRequest, v1.AddProductResponse](
			httpClient,
			baseURL+ProjectServiceAddProductProcedure,
			connect.WithSchema(projectServiceMethods.ByName("AddProduct")),
			connect.WithClientOptions(opts...),
		),
		createCategory: connect.NewClient[v1.CreateCategoryRequest, v1.CreateCategoryResponse](
			httpClient,
			baseURL+ProjectServiceCreateCategoryProcedure,
			connect.WithSchema(projectServiceMethods.ByName("CreateCategory")),
			connect.WithClientOptions(opts...),
		),
		listCategories: connect.NewClient[v1.ListCategoriesRequest, v1.ListCategoriesResponse](
			httpClient,
			baseURL+ProjectServiceListCategoriesProcedure,
			connect.WithSchema(projectServiceMethods.ByName("ListCategories")),
			connect.WithClientOptions(opts...),
		),
		createOrder: connect.NewClient[v1.CreateOrderRequest, v1.CreateOrderResponse](
			httpClient,
			baseURL+ProjectServiceCreateOrderProcedure,
			connect.WithSchema(projectServiceMethods.ByName("CreateOrder")),
			connect.WithClientOptions(opts...),
		),
		cancelOrder: connect.NewClient[v1.CancelOrderRequest, v1.CancelOrderResponse](
			httpClient,
			baseURL+ProjectServiceCancelOrderProcedure,
			connect.WithSchema(projectServiceMethods.ByName("CancelOrder")),
			connect.WithClientOptions(opts...),
		),
		getMyProjectOrder: connect.NewClient[v1.GetMyProjectOrderRequest, v1.GetMyProjectOrderResponse](
			httpClient,
			baseURL+ProjectServiceGetMyProjectOrderProcedure,
			connect.WithSchema(projectServiceMethods.ByName("GetMyProjectOrder")),
			connect.WithClientOptions(opts...),
		),
		updateOrder: connect.NewClient[v1.UpdateOrderRequest, v1.UpdateOrderResponse](
			httpClient,
			baseURL+ProjectServiceUpdateOrderProcedure,
			connect.WithSchema(projectServiceMethods.ByName("UpdateOrder")),
			connect.WithClientOptions(opts...),
		),
		updatePaymentInfo: connect.NewClient[v1.UpdatePaymentInfoRequest, v1.UpdatePaymentInfoResponse](
			httpClient,
			baseURL+ProjectServiceUpdatePaymentInfoProcedure,
			connect.WithSchema(projectServiceMethods.ByName("UpdatePaymentInfo")),
			connect.WithClientOptions(opts...),
		),
		getMyOrders: connect.NewClient[v1.GetMyOrdersRequest, v1.GetMyOrdersResponse](
			httpClient,
			baseURL+ProjectServiceGetMyOrdersProcedure,
			connect.WithSchema(projectServiceMethods.ByName("GetMyOrders")),
			connect.WithClientOptions(opts...),
		),
		batchUpdateStatus: connect.NewClient[v1.BatchUpdateStatusRequest, v1.BatchUpdateStatusResponse](
			httpClient,
			baseURL+ProjectServiceBatchUpdateStatusProcedure,
			connect.WithSchema(projectServiceMethods.ByName("BatchUpdateStatus")),
			connect.WithClientOptions(opts...),
		),
		confirmPayment: connect.NewClient[v1.ConfirmPaymentRequest, v1.ConfirmPaymentResponse](
			httpClient,
			baseURL+ProjectServiceConfirmPaymentProcedure,
			connect.WithSchema(projectServiceMethods.ByName("ConfirmPayment")),
			connect.WithClientOptions(opts...),
		),
		listProjectOrders: connect.NewClient[v1.ListProjectOrdersRequest, v1.ListProjectOrdersResponse](
			httpClient,
			baseURL+ProjectServiceListProjectOrdersProcedure,
			connect.WithSchema(projectServiceMethods.ByName("ListProjectOrders")),
			connect.WithClientOptions(opts...),
		),
		createPriceTemplate: connect.NewClient[v1.CreatePriceTemplateRequest, v1.CreatePriceTemplateResponse](
			httpClient,
			baseURL+ProjectServiceCreatePriceTemplateProcedure,
			connect.WithSchema(projectServiceMethods.ByName("CreatePriceTemplate")),
			connect.WithClientOptions(opts...),
		),
		listPriceTemplates: connect.NewClient[v1.ListPriceTemplatesRequest, v1.ListPriceTemplatesResponse](
			httpClient,
			baseURL+ProjectServiceListPriceTemplatesProcedure,
			connect.WithSchema(projectServiceMethods.ByName("ListPriceTemplates")),
			connect.WithClientOptions(opts...),
		),
		getPriceTemplate: connect.NewClient[v1.GetPriceTemplateRequest, v1.GetPriceTemplateResponse](
			httpClient,
			baseURL+ProjectServiceGetPriceTemplateProcedure,
			connect.WithSchema(projectServiceMethods.ByName("GetPriceTemplate")),
			connect.WithClientOptions(opts...),
		),
		updatePriceTemplate: connect.NewClient[v1.UpdatePriceTemplateRequest, v1.UpdatePriceTemplateResponse](
			httpClient,
			baseURL+ProjectServiceUpdatePriceTemplateProcedure,
			connect.WithSchema(projectServiceMethods.ByName("UpdatePriceTemplate")),
			connect.WithClientOptions(opts...),
		),
		deletePriceTemplate: connect.NewClient[v1.DeletePriceTemplateRequest, v1.DeletePriceTemplateResponse](
			httpClient,
			baseURL+ProjectServiceDeletePriceTemplateProcedure,
			connect.WithSchema(projectServiceMethods.ByName("DeletePriceTemplate")),
			connect.WithClientOptions(opts...),
		),
	}
}

// projectServiceClient implements ProjectServiceClient.
type projectServiceClient struct {
	createProject       *connect.Client[v1.CreateProjectRequest, v1.CreateProjectResponse]
	listProjects        *connect.Client[v1.ListProjectsRequest, v1.ListProjectsResponse]
	listManagerProjects *connect.Client[v1.ListManagerProjectsRequest, v1.ListManagerProjectsResponse]
	getProject          *connect.Client[v1.GetProjectRequest, v1.GetProjectResponse]
	updateProject       *connect.Client[v1.UpdateProjectRequest, v1.UpdateProjectResponse]
	addProduct          *connect.Client[v1.AddProductRequest, v1.AddProductResponse]
	createCategory      *connect.Client[v1.CreateCategoryRequest, v1.CreateCategoryResponse]
	listCategories      *connect.Client[v1.ListCategoriesRequest, v1.ListCategoriesResponse]
	createOrder         *connect.Client[v1.CreateOrderRequest, v1.CreateOrderResponse]
	cancelOrder         *connect.Client[v1.CancelOrderRequest, v1.CancelOrderResponse]
	getMyProjectOrder   *connect.Client[v1.GetMyProjectOrderRequest, v1.GetMyProjectOrderResponse]
	updateOrder         *connect.Client[v1.UpdateOrderRequest, v1.UpdateOrderResponse]
	updatePaymentInfo   *connect.Client[v1.UpdatePaymentInfoRequest, v1.UpdatePaymentInfoResponse]
	getMyOrders         *connect.Client[v1.GetMyOrdersRequest, v1.GetMyOrdersResponse]
	batchUpdateStatus   *connect.Client[v1.BatchUpdateStatusRequest, v1.BatchUpdateStatusResponse]
	confirmPayment      *connect.Client[v1.ConfirmPaymentRequest, v1.ConfirmPaymentResponse]
	listProjectOrders   *connect.Client[v1.ListProjectOrdersRequest, v1.ListProjectOrdersResponse]
	createPriceTemplate *connect.Client[v1.CreatePriceTemplateRequest, v1.CreatePriceTemplateResponse]
	listPriceTemplates  *connect.Client[v1.ListPriceTemplatesRequest, v1.ListPriceTemplatesResponse]
	getPriceTemplate    *connect.Client[v1.GetPriceTemplateRequest, v1.GetPriceTemplateResponse]
	updatePriceTemplate *connect.Client[v1.UpdatePriceTemplateRequest, v1.UpdatePriceTemplateResponse]
	deletePriceTemplate *connect.Client[v1.DeletePriceTemplateRequest, v1.DeletePriceTemplateResponse]
}

// CreateProject calls buygo.v1.ProjectService.CreateProject.
func (c *projectServiceClient) CreateProject(ctx context.Context, req *connect.Request[v1.CreateProjectRequest]) (*connect.Response[v1.CreateProjectResponse], error) {
	return c.createProject.CallUnary(ctx, req)
}

// ListProjects calls buygo.v1.ProjectService.ListProjects.
func (c *projectServiceClient) ListProjects(ctx context.Context, req *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error) {
	return c.listProjects.CallUnary(ctx, req)
}

// ListManagerProjects calls buygo.v1.ProjectService.ListManagerProjects.
func (c *projectServiceClient) ListManagerProjects(ctx context.Context, req *connect.Request[v1.ListManagerProjectsRequest]) (*connect.Response[v1.ListManagerProjectsResponse], error) {
	return c.listManagerProjects.CallUnary(ctx, req)
}

// GetProject calls buygo.v1.ProjectService.GetProject.
func (c *projectServiceClient) GetProject(ctx context.Context, req *connect.Request[v1.GetProjectRequest]) (*connect.Response[v1.GetProjectResponse], error) {
	return c.getProject.CallUnary(ctx, req)
}

// UpdateProject calls buygo.v1.ProjectService.UpdateProject.
func (c *projectServiceClient) UpdateProject(ctx context.Context, req *connect.Request[v1.UpdateProjectRequest]) (*connect.Response[v1.UpdateProjectResponse], error) {
	return c.updateProject.CallUnary(ctx, req)
}

// AddProduct calls buygo.v1.ProjectService.AddProduct.
func (c *projectServiceClient) AddProduct(ctx context.Context, req *connect.Request[v1.AddProductRequest]) (*connect.Response[v1.AddProductResponse], error) {
	return c.addProduct.CallUnary(ctx, req)
}

// CreateCategory calls buygo.v1.ProjectService.CreateCategory.
func (c *projectServiceClient) CreateCategory(ctx context.Context, req *connect.Request[v1.CreateCategoryRequest]) (*connect.Response[v1.CreateCategoryResponse], error) {
	return c.createCategory.CallUnary(ctx, req)
}

// ListCategories calls buygo.v1.ProjectService.ListCategories.
func (c *projectServiceClient) ListCategories(ctx context.Context, req *connect.Request[v1.ListCategoriesRequest]) (*connect.Response[v1.ListCategoriesResponse], error) {
	return c.listCategories.CallUnary(ctx, req)
}

// CreateOrder calls buygo.v1.ProjectService.CreateOrder.
func (c *projectServiceClient) CreateOrder(ctx context.Context, req *connect.Request[v1.CreateOrderRequest]) (*connect.Response[v1.CreateOrderResponse], error) {
	return c.createOrder.CallUnary(ctx, req)
}

// CancelOrder calls buygo.v1.ProjectService.CancelOrder.
func (c *projectServiceClient) CancelOrder(ctx context.Context, req *connect.Request[v1.CancelOrderRequest]) (*connect.Response[v1.CancelOrderResponse], error) {
	return c.cancelOrder.CallUnary(ctx, req)
}

// GetMyProjectOrder calls buygo.v1.ProjectService.GetMyProjectOrder.
func (c *projectServiceClient) GetMyProjectOrder(ctx context.Context, req *connect.Request[v1.GetMyProjectOrderRequest]) (*connect.Response[v1.GetMyProjectOrderResponse], error) {
	return c.getMyProjectOrder.CallUnary(ctx, req)
}

// UpdateOrder calls buygo.v1.ProjectService.UpdateOrder.
func (c *projectServiceClient) UpdateOrder(ctx context.Context, req *connect.Request[v1.UpdateOrderRequest]) (*connect.Response[v1.UpdateOrderResponse], error) {
	return c.updateOrder.CallUnary(ctx, req)
}

// UpdatePaymentInfo calls buygo.v1.ProjectService.UpdatePaymentInfo.
func (c *projectServiceClient) UpdatePaymentInfo(ctx context.Context, req *connect.Request[v1.UpdatePaymentInfoRequest]) (*connect.Response[v1.UpdatePaymentInfoResponse], error) {
	return c.updatePaymentInfo.CallUnary(ctx, req)
}

// GetMyOrders calls buygo.v1.ProjectService.GetMyOrders.
func (c *projectServiceClient) GetMyOrders(ctx context.Context, req *connect.Request[v1.GetMyOrdersRequest]) (*connect.Response[v1.GetMyOrdersResponse], error) {
	return c.getMyOrders.CallUnary(ctx, req)
}

// BatchUpdateStatus calls buygo.v1.ProjectService.BatchUpdateStatus.
func (c *projectServiceClient) BatchUpdateStatus(ctx context.Context, req *connect.Request[v1.BatchUpdateStatusRequest]) (*connect.Response[v1.BatchUpdateStatusResponse], error) {
	return c.batchUpdateStatus.CallUnary(ctx, req)
}

// ConfirmPayment calls buygo.v1.ProjectService.ConfirmPayment.
func (c *projectServiceClient) ConfirmPayment(ctx context.Context, req *connect.Request[v1.ConfirmPaymentRequest]) (*connect.Response[v1.ConfirmPaymentResponse], error) {
	return c.confirmPayment.CallUnary(ctx, req)
}

// ListProjectOrders calls buygo.v1.ProjectService.ListProjectOrders.
func (c *projectServiceClient) ListProjectOrders(ctx context.Context, req *connect.Request[v1.ListProjectOrdersRequest]) (*connect.Response[v1.ListProjectOrdersResponse], error) {
	return c.listProjectOrders.CallUnary(ctx, req)
}

// CreatePriceTemplate calls buygo.v1.ProjectService.CreatePriceTemplate.
func (c *projectServiceClient) CreatePriceTemplate(ctx context.Context, req *connect.Request[v1.CreatePriceTemplateRequest]) (*connect.Response[v1.CreatePriceTemplateResponse], error) {
	return c.createPriceTemplate.CallUnary(ctx, req)
}

// ListPriceTemplates calls buygo.v1.ProjectService.ListPriceTemplates.
func (c *projectServiceClient) ListPriceTemplates(ctx context.Context, req *connect.Request[v1.ListPriceTemplatesRequest]) (*connect.Response[v1.ListPriceTemplatesResponse], error) {
	return c.listPriceTemplates.CallUnary(ctx, req)
}

// GetPriceTemplate calls buygo.v1.ProjectService.GetPriceTemplate.
func (c *projectServiceClient) GetPriceTemplate(ctx context.Context, req *connect.Request[v1.GetPriceTemplateRequest]) (*connect.Response[v1.GetPriceTemplateResponse], error) {
	return c.getPriceTemplate.CallUnary(ctx, req)
}

// UpdatePriceTemplate calls buygo.v1.ProjectService.UpdatePriceTemplate.
func (c *projectServiceClient) UpdatePriceTemplate(ctx context.Context, req *connect.Request[v1.UpdatePriceTemplateRequest]) (*connect.Response[v1.UpdatePriceTemplateResponse], error) {
	return c.updatePriceTemplate.CallUnary(ctx, req)
}

// DeletePriceTemplate calls buygo.v1.ProjectService.DeletePriceTemplate.
func (c *projectServiceClient) DeletePriceTemplate(ctx context.Context, req *connect.Request[v1.DeletePriceTemplateRequest]) (*connect.Response[v1.DeletePriceTemplateResponse], error) {
	return c.deletePriceTemplate.CallUnary(ctx, req)
}

// ProjectServiceHandler is an implementation of the buygo.v1.ProjectService service.
type ProjectServiceHandler interface {
	// Project Management (Creator/Admin)
	CreateProject(context.Context, *connect.Request[v1.CreateProjectRequest]) (*connect.Response[v1.CreateProjectResponse], error)
	ListProjects(context.Context, *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error)
	ListManagerProjects(context.Context, *connect.Request[v1.ListManagerProjectsRequest]) (*connect.Response[v1.ListManagerProjectsResponse], error)
	GetProject(context.Context, *connect.Request[v1.GetProjectRequest]) (*connect.Response[v1.GetProjectResponse], error)
	UpdateProject(context.Context, *connect.Request[v1.UpdateProjectRequest]) (*connect.Response[v1.UpdateProjectResponse], error)
	// Product Management (Creator/Admin)
	AddProduct(context.Context, *connect.Request[v1.AddProductRequest]) (*connect.Response[v1.AddProductResponse], error)
	// Category (Template) Methods
	CreateCategory(context.Context, *connect.Request[v1.CreateCategoryRequest]) (*connect.Response[v1.CreateCategoryResponse], error)
	ListCategories(context.Context, *connect.Request[v1.ListCategoriesRequest]) (*connect.Response[v1.ListCategoriesResponse], error)
	// Order Management (User)
	CreateOrder(context.Context, *connect.Request[v1.CreateOrderRequest]) (*connect.Response[v1.CreateOrderResponse], error)
	CancelOrder(context.Context, *connect.Request[v1.CancelOrderRequest]) (*connect.Response[v1.CancelOrderResponse], error)
	GetMyProjectOrder(context.Context, *connect.Request[v1.GetMyProjectOrderRequest]) (*connect.Response[v1.GetMyProjectOrderResponse], error)
	UpdateOrder(context.Context, *connect.Request[v1.UpdateOrderRequest]) (*connect.Response[v1.UpdateOrderResponse], error)
	UpdatePaymentInfo(context.Context, *connect.Request[v1.UpdatePaymentInfoRequest]) (*connect.Response[v1.UpdatePaymentInfoResponse], error)
	GetMyOrders(context.Context, *connect.Request[v1.GetMyOrdersRequest]) (*connect.Response[v1.GetMyOrdersResponse], error)
	// Order Management (Manager)
	// Batch update status of items (FIFO)
	BatchUpdateStatus(context.Context, *connect.Request[v1.BatchUpdateStatusRequest]) (*connect.Response[v1.BatchUpdateStatusResponse], error)
	// Confirm user payment
	// Confirm user payment
	ConfirmPayment(context.Context, *connect.Request[v1.ConfirmPaymentRequest]) (*connect.Response[v1.ConfirmPaymentResponse], error)
	// Manager: List Orders for a Project
	ListProjectOrders(context.Context, *connect.Request[v1.ListProjectOrdersRequest]) (*connect.Response[v1.ListProjectOrdersResponse], error)
	// Price Templates (Admin Only)
	CreatePriceTemplate(context.Context, *connect.Request[v1.CreatePriceTemplateRequest]) (*connect.Response[v1.CreatePriceTemplateResponse], error)
	ListPriceTemplates(context.Context, *connect.Request[v1.ListPriceTemplatesRequest]) (*connect.Response[v1.ListPriceTemplatesResponse], error)
	GetPriceTemplate(context.Context, *connect.Request[v1.GetPriceTemplateRequest]) (*connect.Response[v1.GetPriceTemplateResponse], error)
	UpdatePriceTemplate(context.Context, *connect.Request[v1.UpdatePriceTemplateRequest]) (*connect.Response[v1.UpdatePriceTemplateResponse], error)
	DeletePriceTemplate(context.Context, *connect.Request[v1.DeletePriceTemplateRequest]) (*connect.Response[v1.DeletePriceTemplateResponse], error)
}

// NewProjectServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProjectServiceHandler(svc ProjectServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	projectServiceMethods := v1.File_api_v1_project_proto.Services().ByName("ProjectService").Methods()
	projectServiceCreateProjectHandler := connect.NewUnaryHandler(
		ProjectServiceCreateProjectProcedure,
		svc.CreateProject,
		connect.WithSchema(projectServiceMethods.ByName("CreateProject")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceListProjectsHandler := connect.NewUnaryHandler(
		ProjectServiceListProjectsProcedure,
		svc.ListProjects,
		connect.WithSchema(projectServiceMethods.ByName("ListProjects")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceListManagerProjectsHandler := connect.NewUnaryHandler(
		ProjectServiceListManagerProjectsProcedure,
		svc.ListManagerProjects,
		connect.WithSchema(projectServiceMethods.ByName("ListManagerProjects")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceGetProjectHandler := connect.NewUnaryHandler(
		ProjectServiceGetProjectProcedure,
		svc.GetProject,
		connect.WithSchema(projectServiceMethods.ByName("GetProject")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceUpdateProjectHandler := connect.NewUnaryHandler(
		ProjectServiceUpdateProjectProcedure,
		svc.UpdateProject,
		connect.WithSchema(projectServiceMethods.ByName("UpdateProject")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceAddProductHandler := connect.NewUnaryHandler(
		ProjectServiceAddProductProcedure,
		svc.AddProduct,
		connect.WithSchema(projectServiceMethods.ByName("AddProduct")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceCreateCategoryHandler := connect.NewUnaryHandler(
		ProjectServiceCreateCategoryProcedure,
		svc.CreateCategory,
		connect.WithSchema(projectServiceMethods.ByName("CreateCategory")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceListCategoriesHandler := connect.NewUnaryHandler(
		ProjectServiceListCategoriesProcedure,
		svc.ListCategories,
		connect.WithSchema(projectServiceMethods.ByName("ListCategories")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceCreateOrderHandler := connect.NewUnaryHandler(
		ProjectServiceCreateOrderProcedure,
		svc.CreateOrder,
		connect.WithSchema(projectServiceMethods.ByName("CreateOrder")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceCancelOrderHandler := connect.NewUnaryHandler(
		ProjectServiceCancelOrderProcedure,
		svc.CancelOrder,
		connect.WithSchema(projectServiceMethods.ByName("CancelOrder")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceGetMyProjectOrderHandler := connect.NewUnaryHandler(
		ProjectServiceGetMyProjectOrderProcedure,
		svc.GetMyProjectOrder,
		connect.WithSchema(projectServiceMethods.ByName("GetMyProjectOrder")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceUpdateOrderHandler := connect.NewUnaryHandler(
		ProjectServiceUpdateOrderProcedure,
		svc.UpdateOrder,
		connect.WithSchema(projectServiceMethods.ByName("UpdateOrder")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceUpdatePaymentInfoHandler := connect.NewUnaryHandler(
		ProjectServiceUpdatePaymentInfoProcedure,
		svc.UpdatePaymentInfo,
		connect.WithSchema(projectServiceMethods.ByName("UpdatePaymentInfo")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceGetMyOrdersHandler := connect.NewUnaryHandler(
		ProjectServiceGetMyOrdersProcedure,
		svc.GetMyOrders,
		connect.WithSchema(projectServiceMethods.ByName("GetMyOrders")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceBatchUpdateStatusHandler := connect.NewUnaryHandler(
		ProjectServiceBatchUpdateStatusProcedure,
		svc.BatchUpdateStatus,
		connect.WithSchema(projectServiceMethods.ByName("BatchUpdateStatus")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceConfirmPaymentHandler := connect.NewUnaryHandler(
		ProjectServiceConfirmPaymentProcedure,
		svc.ConfirmPayment,
		connect.WithSchema(projectServiceMethods.ByName("ConfirmPayment")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceListProjectOrdersHandler := connect.NewUnaryHandler(
		ProjectServiceListProjectOrdersProcedure,
		svc.ListProjectOrders,
		connect.WithSchema(projectServiceMethods.ByName("ListProjectOrders")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceCreatePriceTemplateHandler := connect.NewUnaryHandler(
		ProjectServiceCreatePriceTemplateProcedure,
		svc.CreatePriceTemplate,
		connect.WithSchema(projectServiceMethods.ByName("CreatePriceTemplate")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceListPriceTemplatesHandler := connect.NewUnaryHandler(
		ProjectServiceListPriceTemplatesProcedure,
		svc.ListPriceTemplates,
		connect.WithSchema(projectServiceMethods.ByName("ListPriceTemplates")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceGetPriceTemplateHandler := connect.NewUnaryHandler(
		ProjectServiceGetPriceTemplateProcedure,
		svc.GetPriceTemplate,
		connect.WithSchema(projectServiceMethods.ByName("GetPriceTemplate")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceUpdatePriceTemplateHandler := connect.NewUnaryHandler(
		ProjectServiceUpdatePriceTemplateProcedure,
		svc.UpdatePriceTemplate,
		connect.WithSchema(projectServiceMethods.ByName("UpdatePriceTemplate")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceDeletePriceTemplateHandler := connect.NewUnaryHandler(
		ProjectServiceDeletePriceTemplateProcedure,
		svc.DeletePriceTemplate,
		connect.WithSchema(projectServiceMethods.ByName("DeletePriceTemplate")),
		connect.WithHandlerOptions(opts...),
	)
	return "/buygo.v1.ProjectService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProjectServiceCreateProjectProcedure:
			projectServiceCreateProjectHandler.ServeHTTP(w, r)
		case ProjectServiceListProjectsProcedure:
			projectServiceListProjectsHandler.ServeHTTP(w, r)
		case ProjectServiceListManagerProjectsProcedure:
			projectServiceListManagerProjectsHandler.ServeHTTP(w, r)
		case ProjectServiceGetProjectProcedure:
			projectServiceGetProjectHandler.ServeHTTP(w, r)
		case ProjectServiceUpdateProjectProcedure:
			projectServiceUpdateProjectHandler.ServeHTTP(w, r)
		case ProjectServiceAddProductProcedure:
			projectServiceAddProductHandler.ServeHTTP(w, r)
		case ProjectServiceCreateCategoryProcedure:
			projectServiceCreateCategoryHandler.ServeHTTP(w, r)
		case ProjectServiceListCategoriesProcedure:
			projectServiceListCategoriesHandler.ServeHTTP(w, r)
		case ProjectServiceCreateOrderProcedure:
			projectServiceCreateOrderHandler.ServeHTTP(w, r)
		case ProjectServiceCancelOrderProcedure:
			projectServiceCancelOrderHandler.ServeHTTP(w, r)
		case ProjectServiceGetMyProjectOrderProcedure:
			projectServiceGetMyProjectOrderHandler.ServeHTTP(w, r)
		case ProjectServiceUpdateOrderProcedure:
			projectServiceUpdateOrderHandler.ServeHTTP(w, r)
		case ProjectServiceUpdatePaymentInfoProcedure:
			projectServiceUpdatePaymentInfoHandler.ServeHTTP(w, r)
		case ProjectServiceGetMyOrdersProcedure:
			projectServiceGetMyOrdersHandler.ServeHTTP(w, r)
		case ProjectServiceBatchUpdateStatusProcedure:
			projectServiceBatchUpdateStatusHandler.ServeHTTP(w, r)
		case ProjectServiceConfirmPaymentProcedure:
			projectServiceConfirmPaymentHandler.ServeHTTP(w, r)
		case ProjectServiceListProjectOrdersProcedure:
			projectServiceListProjectOrdersHandler.ServeHTTP(w, r)
		case ProjectServiceCreatePriceTemplateProcedure:
			projectServiceCreatePriceTemplateHandler.ServeHTTP(w, r)
		case ProjectServiceListPriceTemplatesProcedure:
			projectServiceListPriceTemplatesHandler.ServeHTTP(w, r)
		case ProjectServiceGetPriceTemplateProcedure:
			projectServiceGetPriceTemplateHandler.ServeHTTP(w, r)
		case ProjectServiceUpdatePriceTemplateProcedure:
			projectServiceUpdatePriceTemplateHandler.ServeHTTP(w, r)
		case ProjectServiceDeletePriceTemplateProcedure:
			projectServiceDeletePriceTemplateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProjectServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProjectServiceHandler struct{}

func (UnimplementedProjectServiceHandler) CreateProject(context.Context, *connect.Request[v1.CreateProjectRequest]) (*connect.Response[v1.CreateProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.ProjectService.CreateProject is not implemented"))
}

func (UnimplementedProjectServiceHandler) ListProjects(context.Context, *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.ProjectService.ListProjects is not implemented"))
}

func (UnimplementedProjectServiceHandler) ListManagerProjects(context.Context, *connect.Request[v1.ListManagerProjectsRequest]) (*connect.Response[v1.ListManagerProjectsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.ProjectService.ListManagerProjects is not implemented"))
}

func (UnimplementedProjectServiceHandler) GetProject(context.Context, *connect.Request[v1.GetProjectRequest]) (*connect.Response[v1.GetProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.ProjectService.GetProject is not implemented"))
}

func (UnimplementedProjectServiceHandler) UpdateProject(context.Context, *connect.Request[v1.UpdateProjectRequest]) (*connect.Response[v1.UpdateProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.ProjectService.UpdateProject is not implemented"))
}

func (UnimplementedProjectServiceHandler) AddProduct(context.Context, *connect.Request[v1.AddProductRequest]) (*connect.Response[v1.AddProductResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.ProjectService.AddProduct is not implemented"))
}

func (UnimplementedProjectServiceHandler) CreateCategory(context.Context, *connect.Request[v1.CreateCategoryRequest]) (*connect.Response[v1.CreateCategoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.ProjectService.CreateCategory is not implemented"))
}

func (UnimplementedProjectServiceHandler) ListCategories(context.Context, *connect.Request[v1.ListCategoriesRequest]) (*connect.Response[v1.ListCategoriesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.ProjectService.ListCategories is not implemented"))
}

func (UnimplementedProjectServiceHandler) CreateOrder(context.Context, *connect.Request[v1.CreateOrderRequest]) (*connect.Response[v1.CreateOrderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.ProjectService.CreateOrder is not implemented"))
}

func (UnimplementedProjectServiceHandler) CancelOrder(context.Context, *connect.Request[v1.CancelOrderRequest]) (*connect.Response[v1.CancelOrderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.ProjectService.CancelOrder is not implemented"))
}

func (UnimplementedProjectServiceHandler) GetMyProjectOrder(context.Context, *connect.Request[v1.GetMyProjectOrderRequest]) (*connect.Response[v1.GetMyProjectOrderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.ProjectService.GetMyProjectOrder is not implemented"))
}

func (UnimplementedProjectServiceHandler) UpdateOrder(context.Context, *connect.Request[v1.UpdateOrderRequest]) (*connect.Response[v1.UpdateOrderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.ProjectService.UpdateOrder is not implemented"))
}

func (UnimplementedProjectServiceHandler) UpdatePaymentInfo(context.Context, *connect.Request[v1.UpdatePaymentInfoRequest]) (*connect.Response[v1.UpdatePaymentInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.ProjectService.UpdatePaymentInfo is not implemented"))
}

func (UnimplementedProjectServiceHandler) GetMyOrders(context.Context, *connect.Request[v1.GetMyOrdersRequest]) (*connect.Response[v1.GetMyOrdersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.ProjectService.GetMyOrders is not implemented"))
}

func (UnimplementedProjectServiceHandler) BatchUpdateStatus(context.Context, *connect.Request[v1.BatchUpdateStatusRequest]) (*connect.Response[v1.BatchUpdateStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.ProjectService.BatchUpdateStatus is not implemented"))
}

func (UnimplementedProjectServiceHandler) ConfirmPayment(context.Context, *connect.Request[v1.ConfirmPaymentRequest]) (*connect.Response[v1.ConfirmPaymentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.ProjectService.ConfirmPayment is not implemented"))
}

func (UnimplementedProjectServiceHandler) ListProjectOrders(context.Context, *connect.Request[v1.ListProjectOrdersRequest]) (*connect.Response[v1.ListProjectOrdersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.ProjectService.ListProjectOrders is not implemented"))
}

func (UnimplementedProjectServiceHandler) CreatePriceTemplate(context.Context, *connect.Request[v1.CreatePriceTemplateRequest]) (*connect.Response[v1.CreatePriceTemplateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.ProjectService.CreatePriceTemplate is not implemented"))
}

func (UnimplementedProjectServiceHandler) ListPriceTemplates(context.Context, *connect.Request[v1.ListPriceTemplatesRequest]) (*connect.Response[v1.ListPriceTemplatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.ProjectService.ListPriceTemplates is not implemented"))
}

func (UnimplementedProjectServiceHandler) GetPriceTemplate(context.Context, *connect.Request[v1.GetPriceTemplateRequest]) (*connect.Response[v1.GetPriceTemplateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.ProjectService.GetPriceTemplate is not implemented"))
}

func (UnimplementedProjectServiceHandler) UpdatePriceTemplate(context.Context, *connect.Request[v1.UpdatePriceTemplateRequest]) (*connect.Response[v1.UpdatePriceTemplateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.ProjectService.UpdatePriceTemplate is not implemented"))
}

func (UnimplementedProjectServiceHandler) DeletePriceTemplate(context.Context, *connect.Request[v1.DeletePriceTemplateRequest]) (*connect.Response[v1.DeletePriceTemplateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("buygo.v1.ProjectService.DeletePriceTemplate is not implemented"))
}
