package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var (
	serviceRe = regexp.MustCompile(`^\s*service\s+([A-Za-z0-9_]+)\s*\{`)
	rpcRe     = regexp.MustCompile(`^\s*rpc\s+([A-Za-z0-9_]+)\s*\(`)
	accessRe  = regexp.MustCompile(`^\s*//\s*Access:\s*(.+?)\s*$`)
)

type policyEntry struct {
	Constant string
	Access   string
}

func main() {
	root, err := projectRoot()
	must(err)
	protoDir := filepath.Join(root, "api", "v1")

	files, err := filepath.Glob(filepath.Join(protoDir, "*.proto"))
	must(err)
	sort.Strings(files)

	entries := make([]policyEntry, 0, 32)
	for _, file := range files {
		b, readErr := os.ReadFile(file)
		must(readErr)

		currentService := ""
		pendingAccess := ""

		for _, line := range strings.Split(string(b), "\n") {
			if m := accessRe.FindStringSubmatch(line); len(m) == 2 {
				pendingAccess = strings.TrimSpace(m[1])
				continue
			}
			if m := serviceRe.FindStringSubmatch(line); len(m) == 2 {
				currentService = m[1]
				continue
			}
			if m := rpcRe.FindStringSubmatch(line); len(m) == 2 {
				method := m[1]
				entries = append(entries, policyEntry{
					Constant: fmt.Sprintf("%s%sProcedure", currentService, method),
					Access:   toAccessLevel(pendingAccess),
				})
				pendingAccess = ""
			}
		}
	}

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Constant < entries[j].Constant
	})

	var out bytes.Buffer
	out.WriteString("// Code generated by scripts/gen_auth_policy.go; DO NOT EDIT.\n")
	out.WriteString("package interceptor\n\n")
	out.WriteString("import \"github.com/hatsubosi/buygo-api/api/v1/buygov1connect\"\n\n")
	out.WriteString("var procedureAccessPolicy = map[string]accessLevel{\n")
	for _, e := range entries {
		out.WriteString(fmt.Sprintf("\tbuygov1connect.%s: %s,\n", e.Constant, e.Access))
	}
	out.WriteString("}\n")

	target := filepath.Join(root, "internal", "adapter", "interceptor", "auth_policy_generated.go")
	must(os.WriteFile(target, out.Bytes(), 0o644))
}

func projectRoot() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	dir := wd
	for {
		if _, statErr := os.Stat(filepath.Join(dir, "go.mod")); statErr == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found from %s", wd)
		}
		dir = parent
	}
}

func toAccessLevel(accessComment string) string {
	access := strings.ToLower(strings.TrimSpace(accessComment))
	switch {
	case strings.Contains(access, "public"):
		return "accessPublic"
	case access == "admin", strings.Contains(access, "admin only"):
		return "accessSysAdmin"
	default:
		return "accessAuthenticated"
	}
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}
